package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ClassePharma generated by hbm2java
 */
public class ClassePharma implements java.io.Serializable {

	private int classPharmId;
	private String classPharmNom;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public ClassePharma() {
	}

	public ClassePharma(int classPharmId) {
		this.classPharmId = classPharmId;
	}

	public ClassePharma(int classPharmId, String classPharmNom,
			Set<Produit> produits) {
		this.classPharmId = classPharmId;
		this.classPharmNom = classPharmNom;
		this.produits = produits;
	}

	public int getClassPharmId() {
		return this.classPharmId;
	}

	public void setClassPharmId(int classPharmId) {
		this.classPharmId = classPharmId;
	}

	public String getClassPharmNom() {
		return this.classPharmNom;
	}

	public void setClassPharmNom(String classPharmNom) {
		this.classPharmNom = classPharmNom;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
