package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur implements java.io.Serializable {

	private int fourId;
	private String fourDesign1;
	private String fourDesign2;
	private String fourAdresse;
	private String fourTel1;
	private String fourTel2;
	private Set<Operation> operations = new HashSet<Operation>(0);

	public Fournisseur() {
	}

	public Fournisseur(int fourId) {
		this.fourId = fourId;
	}

	public Fournisseur(int fourId, String fourDesign1, String fourDesign2,
			String fourAdresse, String fourTel1, String fourTel2,
			Set<Operation> operations) {
		this.fourId = fourId;
		this.fourDesign1 = fourDesign1;
		this.fourDesign2 = fourDesign2;
		this.fourAdresse = fourAdresse;
		this.fourTel1 = fourTel1;
		this.fourTel2 = fourTel2;
		this.operations = operations;
	}

	public int getFourId() {
		return this.fourId;
	}

	public void setFourId(int fourId) {
		this.fourId = fourId;
	}

	public String getFourDesign1() {
		return this.fourDesign1;
	}

	public void setFourDesign1(String fourDesign1) {
		this.fourDesign1 = fourDesign1;
	}

	public String getFourDesign2() {
		return this.fourDesign2;
	}

	public void setFourDesign2(String fourDesign2) {
		this.fourDesign2 = fourDesign2;
	}

	public String getFourAdresse() {
		return this.fourAdresse;
	}

	public void setFourAdresse(String fourAdresse) {
		this.fourAdresse = fourAdresse;
	}

	public String getFourTel1() {
		return this.fourTel1;
	}

	public void setFourTel1(String fourTel1) {
		this.fourTel1 = fourTel1;
	}

	public String getFourTel2() {
		return this.fourTel2;
	}

	public void setFourTel2(String fourTel2) {
		this.fourTel2 = fourTel2;
	}

	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

}
