package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GestionnairePharma generated by hbm2java
 */
public class GestionnairePharma implements java.io.Serializable {

	private int prepId;
	private String prepNom;
	private String prepPrenom;
	private String prepAdresse;
	private String prepTel;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);
	private Set<Operation> operations = new HashSet<Operation>(0);

	public GestionnairePharma() {
	}

	public GestionnairePharma(int prepId) {
		this.prepId = prepId;
	}

	public GestionnairePharma(int prepId, String prepNom, String prepPrenom,
			String prepAdresse, String prepTel, Set<Ordonnance> ordonnances,
			Set<Operation> operations) {
		this.prepId = prepId;
		this.prepNom = prepNom;
		this.prepPrenom = prepPrenom;
		this.prepAdresse = prepAdresse;
		this.prepTel = prepTel;
		this.ordonnances = ordonnances;
		this.operations = operations;
	}

	public int getPrepId() {
		return this.prepId;
	}

	public void setPrepId(int prepId) {
		this.prepId = prepId;
	}

	public String getPrepNom() {
		return this.prepNom;
	}

	public void setPrepNom(String prepNom) {
		this.prepNom = prepNom;
	}

	public String getPrepPrenom() {
		return this.prepPrenom;
	}

	public void setPrepPrenom(String prepPrenom) {
		this.prepPrenom = prepPrenom;
	}

	public String getPrepAdresse() {
		return this.prepAdresse;
	}

	public void setPrepAdresse(String prepAdresse) {
		this.prepAdresse = prepAdresse;
	}

	public String getPrepTel() {
		return this.prepTel;
	}

	public void setPrepTel(String prepTel) {
		this.prepTel = prepTel;
	}

	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

}
