package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HistoMouvementStock generated by hbm2java
 */
public class HistoMouvementStock implements java.io.Serializable {

	private int mvtId;
	private Produit produit;
	private Integer mvtTypeMvt;
	private Integer mvtQte;
	private Integer mvtProgramme;
	private String mvtLot;
	private String mvtMotif;
	private Date mvtDate;
	private Integer mvtQteStock;

	public HistoMouvementStock() {
	}

	public HistoMouvementStock(int mvtId, Produit produit) {
		this.mvtId = mvtId;
		this.produit = produit;
	}

	public HistoMouvementStock(int mvtId, Produit produit, Integer mvtTypeMvt,
			Integer mvtQte, Integer mvtProgramme, String mvtLot,
			String mvtMotif, Date mvtDate, Integer mvtQteStock) {
		this.mvtId = mvtId;
		this.produit = produit;
		this.mvtTypeMvt = mvtTypeMvt;
		this.mvtQte = mvtQte;
		this.mvtProgramme = mvtProgramme;
		this.mvtLot = mvtLot;
		this.mvtMotif = mvtMotif;
		this.mvtDate = mvtDate;
		this.mvtQteStock = mvtQteStock;
	}

	public int getMvtId() {
		return this.mvtId;
	}

	public void setMvtId(int mvtId) {
		this.mvtId = mvtId;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Integer getMvtTypeMvt() {
		return this.mvtTypeMvt;
	}

	public void setMvtTypeMvt(Integer mvtTypeMvt) {
		this.mvtTypeMvt = mvtTypeMvt;
	}

	public Integer getMvtQte() {
		return this.mvtQte;
	}

	public void setMvtQte(Integer mvtQte) {
		this.mvtQte = mvtQte;
	}

	public Integer getMvtProgramme() {
		return this.mvtProgramme;
	}

	public void setMvtProgramme(Integer mvtProgramme) {
		this.mvtProgramme = mvtProgramme;
	}

	public String getMvtLot() {
		return this.mvtLot;
	}

	public void setMvtLot(String mvtLot) {
		this.mvtLot = mvtLot;
	}

	public String getMvtMotif() {
		return this.mvtMotif;
	}

	public void setMvtMotif(String mvtMotif) {
		this.mvtMotif = mvtMotif;
	}

	public Date getMvtDate() {
		return this.mvtDate;
	}

	public void setMvtDate(Date mvtDate) {
		this.mvtDate = mvtDate;
	}

	public Integer getMvtQteStock() {
		return this.mvtQteStock;
	}

	public void setMvtQteStock(Integer mvtQteStock) {
		this.mvtQteStock = mvtQteStock;
	}

}
