package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

/**
 * LigneDispensationId generated by hbm2java
 */
public class LigneDispensationId implements java.io.Serializable {

	private int ordId;
	private int prodId;

	public LigneDispensationId() {
	}

	public LigneDispensationId(int ordId, int prodId) {
		this.ordId = ordId;
		this.prodId = prodId;
	}

	public int getOrdId() {
		return this.ordId;
	}

	public void setOrdId(int ordId) {
		this.ordId = ordId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LigneDispensationId))
			return false;
		LigneDispensationId castOther = (LigneDispensationId) other;

		return (this.getOrdId() == castOther.getOrdId())
				&& (this.getProdId() == castOther.getProdId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrdId();
		result = 37 * result + this.getProdId();
		return result;
	}

}
