package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

/**
 * LigneDispensation generated by hbm2java
 */
public class LigneDispensation implements java.io.Serializable {

	private LigneDispensationId id;
	private Ordonnance ordonnance;
	private Produit produit;
	private Integer servQteDem;
	private Integer servQteServi;
	private Integer servPrixUnit;

	public LigneDispensation() {
	}

	public LigneDispensation(LigneDispensationId id, Ordonnance ordonnance,
			Produit produit) {
		this.id = id;
		this.ordonnance = ordonnance;
		this.produit = produit;
	}

	public LigneDispensation(LigneDispensationId id, Ordonnance ordonnance,
			Produit produit, Integer servQteDem, Integer servQteServi,
			Integer servPrixUnit) {
		this.id = id;
		this.ordonnance = ordonnance;
		this.produit = produit;
		this.servQteDem = servQteDem;
		this.servQteServi = servQteServi;
		this.servPrixUnit = servPrixUnit;
	}

	public LigneDispensationId getId() {
		return this.id;
	}

	public void setId(LigneDispensationId id) {
		this.id = id;
	}

	public Ordonnance getOrdonnance() {
		return this.ordonnance;
	}

	public void setOrdonnance(Ordonnance ordonnance) {
		this.ordonnance = ordonnance;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Integer getServQteDem() {
		return this.servQteDem;
	}

	public void setServQteDem(Integer servQteDem) {
		this.servQteDem = servQteDem;
	}

	public Integer getServQteServi() {
		return this.servQteServi;
	}

	public void setServQteServi(Integer servQteServi) {
		this.servQteServi = servQteServi;
	}

	public Integer getServPrixUnit() {
		return this.servPrixUnit;
	}

	public void setServPrixUnit(Integer servPrixUnit) {
		this.servPrixUnit = servPrixUnit;
	}

}
