package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

/**
 * LigneInventaire generated by hbm2java
 */
public class LigneInventaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LigneInventaireId id;
	private Programme programme;
	private Inventaire inventaire;
	private Produit produit;
	private Integer qtePhysique;
	private Integer qteLogique;
	private String observation;
	private Integer ecart;

	public LigneInventaire() {
	}

	public LigneInventaire(LigneInventaireId id, Programme programme,
			Inventaire inventaire, Produit produit) {
		this.id = id;
		this.programme = programme;
		this.inventaire = inventaire;
		this.produit = produit;
	}

	public LigneInventaire(LigneInventaireId id, Programme programme,
			Inventaire inventaire, Produit produit, Integer qtePhysique,
			Integer qteLogique, String observation, Integer ecart) {
		this.id = id;
		this.programme = programme;
		this.inventaire = inventaire;
		this.produit = produit;
		this.qtePhysique = qtePhysique;
		this.qteLogique = qteLogique;
		this.observation = observation;
		this.ecart = ecart;
	}

	public LigneInventaireId getId() {
		return this.id;
	}

	public void setId(LigneInventaireId id) {
		this.id = id;
	}

	public Programme getProgramme() {
		return this.programme;
	}

	public void setProgramme(Programme programme) {
		this.programme = programme;
	}

	public Inventaire getInventaire() {
		return this.inventaire;
	}

	public void setInventaire(Inventaire inventaire) {
		this.inventaire = inventaire;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Integer getQtePhysique() {
		return this.qtePhysique;
	}

	public void setQtePhysique(Integer qtePhysique) {
		this.qtePhysique = qtePhysique;
	}

	public Integer getQteLogique() {
		return this.qteLogique;
	}

	public void setQteLogique(Integer qteLogique) {
		this.qteLogique = qteLogique;
	}

	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	public Integer getEcart() {
		return this.ecart;
	}

	public void setEcart(Integer ecart) {
		this.ecart = ecart;
	}

}
