package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

/**
 * LigneInventaireId generated by hbm2java
 */
public class LigneInventaireId implements java.io.Serializable {

	private int invId;
	private int prodId;
	private int programId;

	public LigneInventaireId() {
	}

	public LigneInventaireId(int invId, int prodId, int programId) {
		this.invId = invId;
		this.prodId = prodId;
		this.programId = programId;
	}

	public int getInvId() {
		return this.invId;
	}

	public void setInvId(int invId) {
		this.invId = invId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LigneInventaireId))
			return false;
		LigneInventaireId castOther = (LigneInventaireId) other;

		return (this.getInvId() == castOther.getInvId())
				&& (this.getProdId() == castOther.getProdId())
				&& (this.getProgramId() == castOther.getProgramId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvId();
		result = 37 * result + this.getProdId();
		result = 37 * result + this.getProgramId();
		return result;
	}

}
