package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

/**
 * LingeOperationId generated by hbm2java
 */
public class LingeOperationId implements java.io.Serializable {

	private int prodId;
	private int recptId;

	public LingeOperationId() {
	}

	public LingeOperationId(int prodId, int recptId) {
		this.prodId = prodId;
		this.recptId = recptId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public int getRecptId() {
		return this.recptId;
	}

	public void setRecptId(int recptId) {
		this.recptId = recptId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LingeOperationId))
			return false;
		LingeOperationId castOther = (LingeOperationId) other;

		return (this.getProdId() == castOther.getProdId())
				&& (this.getRecptId() == castOther.getRecptId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProdId();
		result = 37 * result + this.getRecptId();
		return result;
	}

}
