package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Medecin generated by hbm2java
 */
public class Medecin implements java.io.Serializable {

	private int medId;
	private String medCode;
	private String medNom;
	private String medPrenom;
	private String medAdresse;
	private String medTel;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public Medecin() {
	}

	public Medecin(int medId) {
		this.medId = medId;
	}

	public Medecin(int medId, String medCode, String medNom, String medPrenom,
			String medAdresse, String medTel, Set<Ordonnance> ordonnances) {
		this.medId = medId;
		this.medCode = medCode;
		this.medNom = medNom;
		this.medPrenom = medPrenom;
		this.medAdresse = medAdresse;
		this.medTel = medTel;
		this.ordonnances = ordonnances;
	}

	public int getMedId() {
		return this.medId;
	}

	public void setMedId(int medId) {
		this.medId = medId;
	}

	public String getMedCode() {
		return this.medCode;
	}

	public void setMedCode(String medCode) {
		this.medCode = medCode;
	}

	public String getMedNom() {
		return this.medNom;
	}

	public void setMedNom(String medNom) {
		this.medNom = medNom;
	}

	public String getMedPrenom() {
		return this.medPrenom;
	}

	public void setMedPrenom(String medPrenom) {
		this.medPrenom = medPrenom;
	}

	public String getMedAdresse() {
		return this.medAdresse;
	}

	public void setMedAdresse(String medAdresse) {
		this.medAdresse = medAdresse;
	}

	public String getMedTel() {
		return this.medTel;
	}

	public void setMedTel(String medTel) {
		this.medTel = medTel;
	}

	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
