package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordonnance generated by hbm2java
 */
public class Ordonnance implements java.io.Serializable {

	private int ordId;
	private Medecin medecin;
	private Programme programme;
	private GestionnairePharma gestionnairePharma;
	private PatientComplement patientComplement;
	private Regime regime;
	private Date ordDatePrescrip;
	private String ordBut;
	private Date ordDateDispen;
	private Date ordDateSaisi;
	private Integer ordMntTotal;
	private Integer ordNbreJrsTrai;
	private String ordNum;
	private Date ordDateRdv;
	private Set<LigneDispensation> ligneDispensations = new HashSet<LigneDispensation>(
			0);

	public Ordonnance() {
	}

	public Ordonnance(int ordId, GestionnairePharma gestionnairePharma,
			Regime regime) {
		this.ordId = ordId;
		this.gestionnairePharma = gestionnairePharma;
		this.regime = regime;
	}

	public Ordonnance(int ordId, Medecin medecin, Programme programme,
			GestionnairePharma gestionnairePharma,
			PatientComplement patientComplement, Regime regime,
			Date ordDatePrescrip, String ordBut, Date ordDateDispen,
			Date ordDateSaisi, Integer ordMntTotal, Integer ordNbreJrsTrai,
			String ordNum, Date ordDateRdv,
			Set<LigneDispensation> ligneDispensations) {
		this.ordId = ordId;
		this.medecin = medecin;
		this.programme = programme;
		this.gestionnairePharma = gestionnairePharma;
		this.patientComplement = patientComplement;
		this.regime = regime;
		this.ordDatePrescrip = ordDatePrescrip;
		this.ordBut = ordBut;
		this.ordDateDispen = ordDateDispen;
		this.ordDateSaisi = ordDateSaisi;
		this.ordMntTotal = ordMntTotal;
		this.ordNbreJrsTrai = ordNbreJrsTrai;
		this.ordNum = ordNum;
		this.ordDateRdv = ordDateRdv;
		this.ligneDispensations = ligneDispensations;
	}

	public int getOrdId() {
		return this.ordId;
	}

	public void setOrdId(int ordId) {
		this.ordId = ordId;
	}

	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	public Programme getProgramme() {
		return this.programme;
	}

	public void setProgramme(Programme programme) {
		this.programme = programme;
	}

	public GestionnairePharma getGestionnairePharma() {
		return this.gestionnairePharma;
	}

	public void setGestionnairePharma(GestionnairePharma gestionnairePharma) {
		this.gestionnairePharma = gestionnairePharma;
	}

	public PatientComplement getPatientComplement() {
		return this.patientComplement;
	}

	public void setPatientComplement(PatientComplement patientComplement) {
		this.patientComplement = patientComplement;
	}

	public Regime getRegime() {
		return this.regime;
	}

	public void setRegime(Regime regime) {
		this.regime = regime;
	}

	public Date getOrdDatePrescrip() {
		return this.ordDatePrescrip;
	}

	public void setOrdDatePrescrip(Date ordDatePrescrip) {
		this.ordDatePrescrip = ordDatePrescrip;
	}

	public String getOrdBut() {
		return this.ordBut;
	}

	public void setOrdBut(String ordBut) {
		this.ordBut = ordBut;
	}

	public Date getOrdDateDispen() {
		return this.ordDateDispen;
	}

	public void setOrdDateDispen(Date ordDateDispen) {
		this.ordDateDispen = ordDateDispen;
	}

	public Date getOrdDateSaisi() {
		return this.ordDateSaisi;
	}

	public void setOrdDateSaisi(Date ordDateSaisi) {
		this.ordDateSaisi = ordDateSaisi;
	}

	public Integer getOrdMntTotal() {
		return this.ordMntTotal;
	}

	public void setOrdMntTotal(Integer ordMntTotal) {
		this.ordMntTotal = ordMntTotal;
	}

	public Integer getOrdNbreJrsTrai() {
		return this.ordNbreJrsTrai;
	}

	public void setOrdNbreJrsTrai(Integer ordNbreJrsTrai) {
		this.ordNbreJrsTrai = ordNbreJrsTrai;
	}

	public String getOrdNum() {
		return this.ordNum;
	}

	public void setOrdNum(String ordNum) {
		this.ordNum = ordNum;
	}

	public Date getOrdDateRdv() {
		return this.ordDateRdv;
	}

	public void setOrdDateRdv(Date ordDateRdv) {
		this.ordDateRdv = ordDateRdv;
	}

	public Set<LigneDispensation> getLigneDispensations() {
		return this.ligneDispensations;
	}

	public void setLigneDispensations(Set<LigneDispensation> ligneDispensations) {
		this.ligneDispensations = ligneDispensations;
	}

}
