package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 03:03:05 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PatientIdentifier generated by hbm2java
 */
public class PatientIdentifier implements java.io.Serializable {

	private long patientIdentifierId;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public PatientIdentifier() {
	}

	public PatientIdentifier(long patientIdentifierId) {
		this.patientIdentifierId = patientIdentifierId;
	}

	public PatientIdentifier(long patientIdentifierId,
			Set<Ordonnance> ordonnances) {
		this.patientIdentifierId = patientIdentifierId;
		this.ordonnances = ordonnances;
	}

	public long getPatientIdentifierId() {
		return this.patientIdentifierId;
	}

	public void setPatientIdentifierId(long patientIdentifierId) {
		this.patientIdentifierId = patientIdentifierId;
	}

	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
