package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PatientComplement generated by hbm2java
 */
public class PatientComplement implements java.io.Serializable {

	private long patientIdentifierId;
	private Regime regime;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public PatientComplement() {
	}

	public PatientComplement(long patientIdentifierId) {
		this.patientIdentifierId = patientIdentifierId;
	}

	public PatientComplement(long patientIdentifierId, Regime regime,
			Set<Ordonnance> ordonnances) {
		this.patientIdentifierId = patientIdentifierId;
		this.regime = regime;
		this.ordonnances = ordonnances;
	}

	public long getPatientIdentifierId() {
		return this.patientIdentifierId;
	}

	public void setPatientIdentifierId(long patientIdentifierId) {
		this.patientIdentifierId = patientIdentifierId;
	}

	public Regime getRegime() {
		return this.regime;
	}

	public void setRegime(Regime regime) {
		this.regime = regime;
	}

	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
