package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PharmLigneOperation generated by hbm2java
 */
public class PharmLigneOperation implements java.io.Serializable {

	private PharmLigneOperationId id;
	private PharmProduitAttribut pharmProduitAttribut;
	private PharmOperation pharmOperation;
	private Integer lgnOperQte;
	private Integer lgnOperPrixAchat;
	private Date lgnOperDatePerem;
	private String lgnOperLot;

	public PharmLigneOperation() {
	}

	public PharmLigneOperation(PharmLigneOperationId id,
			PharmProduitAttribut pharmProduitAttribut,
			PharmOperation pharmOperation) {
		this.id = id;
		this.pharmProduitAttribut = pharmProduitAttribut;
		this.pharmOperation = pharmOperation;
	}

	public PharmLigneOperation(PharmLigneOperationId id,
			PharmProduitAttribut pharmProduitAttribut,
			PharmOperation pharmOperation, Integer lgnOperQte,
			Integer lgnOperPrixAchat, Date lgnOperDatePerem, String lgnOperLot) {
		this.id = id;
		this.pharmProduitAttribut = pharmProduitAttribut;
		this.pharmOperation = pharmOperation;
		this.lgnOperQte = lgnOperQte;
		this.lgnOperPrixAchat = lgnOperPrixAchat;
		this.lgnOperDatePerem = lgnOperDatePerem;
		this.lgnOperLot = lgnOperLot;
	}

	public PharmLigneOperationId getId() {
		return this.id;
	}

	public void setId(PharmLigneOperationId id) {
		this.id = id;
	}

	public PharmProduitAttribut getPharmProduitAttribut() {
		return this.pharmProduitAttribut;
	}

	public void setPharmProduitAttribut(
			PharmProduitAttribut pharmProduitAttribut) {
		this.pharmProduitAttribut = pharmProduitAttribut;
	}

	public PharmOperation getPharmOperation() {
		return this.pharmOperation;
	}

	public void setPharmOperation(PharmOperation pharmOperation) {
		this.pharmOperation = pharmOperation;
	}

	public Integer getLgnOperQte() {
		return this.lgnOperQte;
	}

	public void setLgnOperQte(Integer lgnOperQte) {
		this.lgnOperQte = lgnOperQte;
	}

	public Integer getLgnOperPrixAchat() {
		return this.lgnOperPrixAchat;
	}

	public void setLgnOperPrixAchat(Integer lgnOperPrixAchat) {
		this.lgnOperPrixAchat = lgnOperPrixAchat;
	}

	public Date getLgnOperDatePerem() {
		return this.lgnOperDatePerem;
	}

	public void setLgnOperDatePerem(Date lgnOperDatePerem) {
		this.lgnOperDatePerem = lgnOperDatePerem;
	}

	public String getLgnOperLot() {
		return this.lgnOperLot;
	}

	public void setLgnOperLot(String lgnOperLot) {
		this.lgnOperLot = lgnOperLot;
	}

}
