package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PharmHistoMouvementStock generated by hbm2java
 */
public class PharmHistoMouvementStock implements java.io.Serializable {

	private Integer mvtId;
	private PharmProduit pharmProduit;
	private Integer mvtTypeMvt;
	private Integer mvtQte;
	private Integer mvtProgramme;
	private String mvtLot;
	private String mvtMotif;
	private Date mvtDate;
	private Integer mvtQteStock;

	public PharmHistoMouvementStock() {
	}

	public PharmHistoMouvementStock(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public PharmHistoMouvementStock(PharmProduit pharmProduit,
			Integer mvtTypeMvt, Integer mvtQte, Integer mvtProgramme,
			String mvtLot, String mvtMotif, Date mvtDate, Integer mvtQteStock) {
		this.pharmProduit = pharmProduit;
		this.mvtTypeMvt = mvtTypeMvt;
		this.mvtQte = mvtQte;
		this.mvtProgramme = mvtProgramme;
		this.mvtLot = mvtLot;
		this.mvtMotif = mvtMotif;
		this.mvtDate = mvtDate;
		this.mvtQteStock = mvtQteStock;
	}

	public Integer getMvtId() {
		return this.mvtId;
	}

	public void setMvtId(Integer mvtId) {
		this.mvtId = mvtId;
	}

	public PharmProduit getPharmProduit() {
		return this.pharmProduit;
	}

	public void setPharmProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public Integer getMvtTypeMvt() {
		return this.mvtTypeMvt;
	}

	public void setMvtTypeMvt(Integer mvtTypeMvt) {
		this.mvtTypeMvt = mvtTypeMvt;
	}

	public Integer getMvtQte() {
		return this.mvtQte;
	}

	public void setMvtQte(Integer mvtQte) {
		this.mvtQte = mvtQte;
	}

	public Integer getMvtProgramme() {
		return this.mvtProgramme;
	}

	public void setMvtProgramme(Integer mvtProgramme) {
		this.mvtProgramme = mvtProgramme;
	}

	public String getMvtLot() {
		return this.mvtLot;
	}

	public void setMvtLot(String mvtLot) {
		this.mvtLot = mvtLot;
	}

	public String getMvtMotif() {
		return this.mvtMotif;
	}

	public void setMvtMotif(String mvtMotif) {
		this.mvtMotif = mvtMotif;
	}

	public Date getMvtDate() {
		return this.mvtDate;
	}

	public void setMvtDate(Date mvtDate) {
		this.mvtDate = mvtDate;
	}

	public Integer getMvtQteStock() {
		return this.mvtQteStock;
	}

	public void setMvtQteStock(Integer mvtQteStock) {
		this.mvtQteStock = mvtQteStock;
	}

}
