package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PharmFournisseur generated by hbm2java
 */
public class PharmFournisseur implements java.io.Serializable {

	private Integer fourId;
	private String fourDesign1;
	private String fourDesign2;
	private String fourAdresse;
	private String fourTel1;
	private String fourTel2;
	private Set<PharmOperation> pharmOperations = new HashSet<PharmOperation>(0);

	public PharmFournisseur() {
	}

	public PharmFournisseur(String fourDesign1, String fourDesign2,
			String fourAdresse, String fourTel1, String fourTel2,
			Set<PharmOperation> pharmOperations) {
		this.fourDesign1 = fourDesign1;
		this.fourDesign2 = fourDesign2;
		this.fourAdresse = fourAdresse;
		this.fourTel1 = fourTel1;
		this.fourTel2 = fourTel2;
		this.pharmOperations = pharmOperations;
	}

	public Integer getFourId() {
		return this.fourId;
	}

	public void setFourId(Integer fourId) {
		this.fourId = fourId;
	}

	public String getFourDesign1() {
		return this.fourDesign1;
	}

	public void setFourDesign1(String fourDesign1) {
		this.fourDesign1 = fourDesign1;
	}

	public String getFourDesign2() {
		return this.fourDesign2;
	}

	public void setFourDesign2(String fourDesign2) {
		this.fourDesign2 = fourDesign2;
	}

	public String getFourAdresse() {
		return this.fourAdresse;
	}

	public void setFourAdresse(String fourAdresse) {
		this.fourAdresse = fourAdresse;
	}

	public String getFourTel1() {
		return this.fourTel1;
	}

	public void setFourTel1(String fourTel1) {
		this.fourTel1 = fourTel1;
	}

	public String getFourTel2() {
		return this.fourTel2;
	}

	public void setFourTel2(String fourTel2) {
		this.fourTel2 = fourTel2;
	}

	public Set<PharmOperation> getPharmOperations() {
		return this.pharmOperations;
	}

	public void setPharmOperations(Set<PharmOperation> pharmOperations) {
		this.pharmOperations = pharmOperations;
	}

}
