package org.openmrs.module.pharmagest;
// Generated 24 mai 2017 16:53:10 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneAssuranceId generated by hbm2java
 */
public class PharmLigneAssuranceId implements java.io.Serializable {

	private int assurId;
	private int cliId;

	public PharmLigneAssuranceId() {
	}

	public PharmLigneAssuranceId(int assurId, int cliId) {
		this.assurId = assurId;
		this.cliId = cliId;
	}

	public int getAssurId() {
		return this.assurId;
	}

	public void setAssurId(int assurId) {
		this.assurId = assurId;
	}

	public int getCliId() {
		return this.cliId;
	}

	public void setCliId(int cliId) {
		this.cliId = cliId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmLigneAssuranceId))
			return false;
		PharmLigneAssuranceId castOther = (PharmLigneAssuranceId) other;

		return (this.getAssurId() == castOther.getAssurId()) && (this.getCliId() == castOther.getCliId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAssurId();
		result = 37 * result + this.getCliId();
		return result;
	}

}
