package org.openmrs.module.pharmagest;
// Generated 16 mai 2017 05:51:27 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneReceptionId generated by hbm2java
 */
public class PharmLigneReceptionId implements java.io.Serializable {

	private int prodAttriId;
	private int recptId;

	public PharmLigneReceptionId() {
	}

	public PharmLigneReceptionId(int prodAttriId, int recptId) {
		this.prodAttriId = prodAttriId;
		this.recptId = recptId;
	}

	public int getProdAttriId() {
		return this.prodAttriId;
	}

	public void setProdAttriId(int prodAttriId) {
		this.prodAttriId = prodAttriId;
	}

	public int getRecptId() {
		return this.recptId;
	}

	public void setRecptId(int recptId) {
		this.recptId = recptId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmLigneReceptionId))
			return false;
		PharmLigneReceptionId castOther = (PharmLigneReceptionId) other;

		return (this.getProdAttriId() == castOther.getProdAttriId()) && (this.getRecptId() == castOther.getRecptId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProdAttriId();
		result = 37 * result + this.getRecptId();
		return result;
	}

}
