package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PharmClassePharma generated by hbm2java
 */
public class PharmClassePharma implements java.io.Serializable {

	private Integer classPharmId;
	private String classPharmNom;
	private Set<PharmProduit> pharmProduits = new HashSet<PharmProduit>(0);

	public PharmClassePharma() {
	}

	public PharmClassePharma(String classPharmNom,
			Set<PharmProduit> pharmProduits) {
		this.classPharmNom = classPharmNom;
		this.pharmProduits = pharmProduits;
	}

	public Integer getClassPharmId() {
		return this.classPharmId;
	}

	public void setClassPharmId(Integer classPharmId) {
		this.classPharmId = classPharmId;
	}

	public String getClassPharmNom() {
		return this.classPharmNom;
	}

	public void setClassPharmNom(String classPharmNom) {
		this.classPharmNom = classPharmNom;
	}

	public Set<PharmProduit> getPharmProduits() {
		return this.pharmProduits;
	}

	public void setPharmProduits(Set<PharmProduit> pharmProduits) {
		this.pharmProduits = pharmProduits;
	}

}
