package org.openmrs.module.pharmagest;
// Generated 24 mai 2017 16:53:10 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmClient generated by hbm2java
 */
public class PharmClient implements java.io.Serializable {

	private int cliId;
	private String cliNom;
	private String cliPrenom;
	private Date cliDateNaiss;
	private String cliGenre;
	private String cliTel1;
	private String cliTel2;
	private Date cliDateSaisi;
	private Date cliDateModif;
	private String cliType;
	private String cliPatientRef;
	private Set<PharmOrdonnance> pharmOrdonnances = new HashSet<PharmOrdonnance>(0);
	private Set<PharmLigneAssurance> pharmLigneAssurances = new HashSet<PharmLigneAssurance>(0);

	public PharmClient() {
	}

	public PharmClient(int cliId) {
		this.cliId = cliId;
	}

	public PharmClient(int cliId, String cliNom, String cliPrenom, Date cliDateNaiss, String cliGenre, String cliTel1,
			String cliTel2, Date cliDateSaisi, Date cliDateModif, String cliType, String cliPatientRef,
			Set<PharmOrdonnance> pharmOrdonnances, Set<PharmLigneAssurance> pharmLigneAssurances) {
		this.cliId = cliId;
		this.cliNom = cliNom;
		this.cliPrenom = cliPrenom;
		this.cliDateNaiss = cliDateNaiss;
		this.cliGenre = cliGenre;
		this.cliTel1 = cliTel1;
		this.cliTel2 = cliTel2;
		this.cliDateSaisi = cliDateSaisi;
		this.cliDateModif = cliDateModif;
		this.cliType = cliType;
		this.cliPatientRef = cliPatientRef;
		this.pharmOrdonnances = pharmOrdonnances;
		this.pharmLigneAssurances = pharmLigneAssurances;
	}

	public int getCliId() {
		return this.cliId;
	}

	public void setCliId(int cliId) {
		this.cliId = cliId;
	}

	public String getCliNom() {
		return this.cliNom;
	}

	public void setCliNom(String cliNom) {
		this.cliNom = cliNom;
	}

	public String getCliPrenom() {
		return this.cliPrenom;
	}

	public void setCliPrenom(String cliPrenom) {
		this.cliPrenom = cliPrenom;
	}

	public Date getCliDateNaiss() {
		return this.cliDateNaiss;
	}

	public void setCliDateNaiss(Date cliDateNaiss) {
		this.cliDateNaiss = cliDateNaiss;
	}

	public String getCliGenre() {
		return this.cliGenre;
	}

	public void setCliGenre(String cliGenre) {
		this.cliGenre = cliGenre;
	}

	public String getCliTel1() {
		return this.cliTel1;
	}

	public void setCliTel1(String cliTel1) {
		this.cliTel1 = cliTel1;
	}

	public String getCliTel2() {
		return this.cliTel2;
	}

	public void setCliTel2(String cliTel2) {
		this.cliTel2 = cliTel2;
	}

	public Date getCliDateSaisi() {
		return this.cliDateSaisi;
	}

	public void setCliDateSaisi(Date cliDateSaisi) {
		this.cliDateSaisi = cliDateSaisi;
	}

	public Date getCliDateModif() {
		return this.cliDateModif;
	}

	public void setCliDateModif(Date cliDateModif) {
		this.cliDateModif = cliDateModif;
	}

	public String getCliType() {
		return this.cliType;
	}

	public void setCliType(String cliType) {
		this.cliType = cliType;
	}

	public String getCliPatientRef() {
		return this.cliPatientRef;
	}

	public void setCliPatientRef(String cliPatientRef) {
		this.cliPatientRef = cliPatientRef;
	}

	public Set<PharmOrdonnance> getPharmOrdonnances() {
		return this.pharmOrdonnances;
	}

	public void setPharmOrdonnances(Set<PharmOrdonnance> pharmOrdonnances) {
		this.pharmOrdonnances = pharmOrdonnances;
	}

	public Set<PharmLigneAssurance> getPharmLigneAssurances() {
		return this.pharmLigneAssurances;
	}

	public void setPharmLigneAssurances(Set<PharmLigneAssurance> pharmLigneAssurances) {
		this.pharmLigneAssurances = pharmLigneAssurances;
	}

}
