package org.openmrs.module.pharmagest;
// Generated 3 f�vr. 2016 16:54:55 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneRc generated by hbm2java
 */
public class PharmLigneRc implements java.io.Serializable {

	private PharmLigneRcId id;
	private PharmProduit pharmProduit;
	private PharmRapportCommande pharmRapportCommande;
	private Integer lgnRcStockIni;
	private Integer lgnRcQteRecu;
	private Integer lgnRcQteUtil;
	private Integer lgnRcPerte;
	private Integer lgnRcAjust;
	private Integer lgnRcStockDispo;
	private Integer lgnRcJrsRup;
	private Integer lgnRcSiteRup;
	private Integer lgnRcConsoMoyenMens;
	private Double lgnRcMoisStockDispo;
	private Integer lgnRcQteCom;
	private Integer lgnRcQteAcc;

	public PharmLigneRc() {
	}

	public PharmLigneRc(PharmLigneRcId id, PharmProduit pharmProduit, PharmRapportCommande pharmRapportCommande) {
		this.id = id;
		this.pharmProduit = pharmProduit;
		this.pharmRapportCommande = pharmRapportCommande;
	}

	public PharmLigneRc(PharmLigneRcId id, PharmProduit pharmProduit, PharmRapportCommande pharmRapportCommande,
			Integer lgnRcStockIni, Integer lgnRcQteRecu, Integer lgnRcQteUtil, Integer lgnRcPerte, Integer lgnRcAjust,
			Integer lgnRcStockDispo, Integer lgnRcJrsRup, Integer lgnRcSiteRup, Integer lgnRcConsoMoyenMens,
			Double lgnRcMoisStockDispo, Integer lgnRcQteCom, Integer lgnRcQteAcc) {
		this.id = id;
		this.pharmProduit = pharmProduit;
		this.pharmRapportCommande = pharmRapportCommande;
		this.lgnRcStockIni = lgnRcStockIni;
		this.lgnRcQteRecu = lgnRcQteRecu;
		this.lgnRcQteUtil = lgnRcQteUtil;
		this.lgnRcPerte = lgnRcPerte;
		this.lgnRcAjust = lgnRcAjust;
		this.lgnRcStockDispo = lgnRcStockDispo;
		this.lgnRcJrsRup = lgnRcJrsRup;
		this.lgnRcSiteRup = lgnRcSiteRup;
		this.lgnRcConsoMoyenMens = lgnRcConsoMoyenMens;
		this.lgnRcMoisStockDispo = lgnRcMoisStockDispo;
		this.lgnRcQteCom = lgnRcQteCom;
		this.lgnRcQteAcc = lgnRcQteAcc;
	}

	public PharmLigneRcId getId() {
		return this.id;
	}

	public void setId(PharmLigneRcId id) {
		this.id = id;
	}

	public PharmProduit getPharmProduit() {
		return this.pharmProduit;
	}

	public void setPharmProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public PharmRapportCommande getPharmRapportCommande() {
		return this.pharmRapportCommande;
	}

	public void setPharmRapportCommande(PharmRapportCommande pharmRapportCommande) {
		this.pharmRapportCommande = pharmRapportCommande;
	}

	public Integer getLgnRcStockIni() {
		return this.lgnRcStockIni;
	}

	public void setLgnRcStockIni(Integer lgnRcStockIni) {
		this.lgnRcStockIni = lgnRcStockIni;
	}

	public Integer getLgnRcQteRecu() {
		return this.lgnRcQteRecu;
	}

	public void setLgnRcQteRecu(Integer lgnRcQteRecu) {
		this.lgnRcQteRecu = lgnRcQteRecu;
	}

	public Integer getLgnRcQteUtil() {
		return this.lgnRcQteUtil;
	}

	public void setLgnRcQteUtil(Integer lgnRcQteUtil) {
		this.lgnRcQteUtil = lgnRcQteUtil;
	}

	public Integer getLgnRcPerte() {
		return this.lgnRcPerte;
	}

	public void setLgnRcPerte(Integer lgnRcPerte) {
		this.lgnRcPerte = lgnRcPerte;
	}

	public Integer getLgnRcAjust() {
		return this.lgnRcAjust;
	}

	public void setLgnRcAjust(Integer lgnRcAjust) {
		this.lgnRcAjust = lgnRcAjust;
	}

	public Integer getLgnRcStockDispo() {
		return this.lgnRcStockDispo;
	}

	public void setLgnRcStockDispo(Integer lgnRcStockDispo) {
		this.lgnRcStockDispo = lgnRcStockDispo;
	}

	public Integer getLgnRcJrsRup() {
		return this.lgnRcJrsRup;
	}

	public void setLgnRcJrsRup(Integer lgnRcJrsRup) {
		this.lgnRcJrsRup = lgnRcJrsRup;
	}

	public Integer getLgnRcSiteRup() {
		return this.lgnRcSiteRup;
	}

	public void setLgnRcSiteRup(Integer lgnRcSiteRup) {
		this.lgnRcSiteRup = lgnRcSiteRup;
	}

	public Integer getLgnRcConsoMoyenMens() {
		return this.lgnRcConsoMoyenMens;
	}

	public void setLgnRcConsoMoyenMens(Integer lgnRcConsoMoyenMens) {
		this.lgnRcConsoMoyenMens = lgnRcConsoMoyenMens;
	}

	public Double getLgnRcMoisStockDispo() {
		return this.lgnRcMoisStockDispo;
	}

	public void setLgnRcMoisStockDispo(Double lgnRcMoisStockDispo) {
		this.lgnRcMoisStockDispo = lgnRcMoisStockDispo;
	}

	public Integer getLgnRcQteCom() {
		return this.lgnRcQteCom;
	}

	public void setLgnRcQteCom(Integer lgnRcQteCom) {
		this.lgnRcQteCom = lgnRcQteCom;
	}

	public Integer getLgnRcQteAcc() {
		return this.lgnRcQteAcc;
	}

	public void setLgnRcQteAcc(Integer lgnRcQteAcc) {
		this.lgnRcQteAcc = lgnRcQteAcc;
	}

}
