package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PharmGestionnairePharma generated by hbm2java
 */
public class PharmGestionnairePharma implements java.io.Serializable {

	private Integer gestId;
	private String gestNom;
	private String gestPrenom;
	private String gestAdresse;
	private String gestTel;
	private Set<PharmOperation> pharmOperations = new HashSet<PharmOperation>(0);
	private Set<PharmOrdonnance> pharmOrdonnances = new HashSet<PharmOrdonnance>(
			0);

	public PharmGestionnairePharma() {
	}

	public PharmGestionnairePharma(String gestNom, String gestPrenom,
			String gestAdresse, String gestTel,
			Set<PharmOperation> pharmOperations,
			Set<PharmOrdonnance> pharmOrdonnances) {
		this.gestNom = gestNom;
		this.gestPrenom = gestPrenom;
		this.gestAdresse = gestAdresse;
		this.gestTel = gestTel;
		this.pharmOperations = pharmOperations;
		this.pharmOrdonnances = pharmOrdonnances;
	}

	public Integer getGestId() {
		return this.gestId;
	}

	public void setGestId(Integer gestId) {
		this.gestId = gestId;
	}

	public String getGestNom() {
		return this.gestNom;
	}

	public void setGestNom(String gestNom) {
		this.gestNom = gestNom;
	}

	public String getGestPrenom() {
		return this.gestPrenom;
	}

	public void setGestPrenom(String gestPrenom) {
		this.gestPrenom = gestPrenom;
	}

	public String getGestAdresse() {
		return this.gestAdresse;
	}

	public void setGestAdresse(String gestAdresse) {
		this.gestAdresse = gestAdresse;
	}

	public String getGestTel() {
		return this.gestTel;
	}

	public void setGestTel(String gestTel) {
		this.gestTel = gestTel;
	}

	public Set<PharmOperation> getPharmOperations() {
		return this.pharmOperations;
	}

	public void setPharmOperations(Set<PharmOperation> pharmOperations) {
		this.pharmOperations = pharmOperations;
	}

	public Set<PharmOrdonnance> getPharmOrdonnances() {
		return this.pharmOrdonnances;
	}

	public void setPharmOrdonnances(Set<PharmOrdonnance> pharmOrdonnances) {
		this.pharmOrdonnances = pharmOrdonnances;
	}

}
