package org.openmrs.module.pharmagest;

// Generated 16 ao�t 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PharmStocker generated by hbm2java
 */
public class PharmStocker implements java.io.Serializable, java.lang.Comparable {

	private PharmStockerId id;
	private PharmProgramme pharmProgramme;
	private PharmProduitAttribut pharmProduitAttribut;
	private Integer stockQte;
	private Integer stockQteMin;
	private Integer stockQteMax;
	private Date stockDateStock;
	private Date stockDatePeremp;
	private String stockLot;
	private Integer stockQteIni;

	public PharmStocker() {
	}

	public PharmStocker(PharmStockerId id, PharmProgramme pharmProgramme, PharmProduitAttribut pharmProduitAttribut) {
		this.id = id;
		this.pharmProgramme = pharmProgramme;
		this.pharmProduitAttribut = pharmProduitAttribut;
	}

	public PharmStocker(PharmStockerId id, PharmProgramme pharmProgramme, PharmProduitAttribut pharmProduitAttribut,
			Integer stockQte, Integer stockQteMin, Integer stockQteMax, Date stockDateStock, Date stockDatePeremp) {
		this.id = id;
		this.pharmProgramme = pharmProgramme;
		this.pharmProduitAttribut = pharmProduitAttribut;
		this.stockQte = stockQte;
		this.stockQteMin = stockQteMin;
		this.stockQteMax = stockQteMax;
		this.stockDateStock = stockDateStock;
		this.stockDatePeremp = stockDatePeremp;
	}

	public PharmStockerId getId() {
		return this.id;
	}

	public void setId(PharmStockerId id) {
		this.id = id;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public PharmProduitAttribut getPharmProduitAttribut() {
		return this.pharmProduitAttribut;
	}

	public void setPharmProduitAttribut(PharmProduitAttribut pharmProduitAttribut) {
		this.pharmProduitAttribut = pharmProduitAttribut;
	}

	public Integer getStockQte() {
		return this.stockQte;
	}

	public void setStockQte(Integer stockQte) {
		this.stockQte = stockQte;
	}

	public Integer getStockQteMin() {
		return this.stockQteMin;
	}

	public void setStockQteMin(Integer stockQteMin) {
		this.stockQteMin = stockQteMin;
	}

	public Integer getStockQteMax() {
		return this.stockQteMax;
	}

	public void setStockQteMax(Integer stockQteMax) {
		this.stockQteMax = stockQteMax;
	}

	public Date getStockDateStock() {
		return this.stockDateStock;
	}

	public void setStockDateStock(Date stockDateStock) {
		this.stockDateStock = stockDateStock;
	}

	public Date getStockDatePeremp() {
		return this.stockDatePeremp;
	}

	public void setStockDatePeremp(Date stockDatePeremp) {
		this.stockDatePeremp = stockDatePeremp;
	}

	public String getStockLot() {
		return stockLot;
	}

	public void setStockLot(String stockLot) {
		this.stockLot = stockLot;
	}

	public Integer getStockQteIni() {
		return stockQteIni;
	}

	public void setStockQteIni(Integer stockQteIni) {
		this.stockQteIni = stockQteIni;
	}

	@Override
	public int compareTo(Object o) {
		Date datePerem1 = ((PharmStocker) o).getStockDatePeremp();
		Date datePerem2 = this.getStockDatePeremp();
		if (datePerem1 != null && datePerem2 != null) {
			if (datePerem1.compareTo(datePerem2) == 1)
				return 1;
			else if (datePerem1.compareTo(datePerem2) == -1)
				return -1;
			else if (datePerem1.compareTo(datePerem2) == 0)
				return 0;
			return 0;
		}else {
			return 0;
		}
	}

}
