package org.openmrs.module.pharmagest;
// Generated 24 mai 2017 16:53:10 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * PharmLigneAssurance generated by hbm2java
 */
public class PharmLigneAssurance implements java.io.Serializable {

	private PharmLigneAssuranceId id;
	private PharmAssurance pharmAssurance;
	private PharmClient pharmClient;
	private String laNumAssur;
	private Integer laTaux;
	private Date laDateSaisi;
	private Date laDateModif;

	public PharmLigneAssurance() {
	}

	public PharmLigneAssurance(PharmLigneAssuranceId id, PharmAssurance pharmAssurance, PharmClient pharmClient) {
		this.id = id;
		this.pharmAssurance = pharmAssurance;
		this.pharmClient = pharmClient;
	}

	public PharmLigneAssurance(PharmLigneAssuranceId id, PharmAssurance pharmAssurance, PharmClient pharmClient,
			String laNumAssur, Integer laTaux, Date laDateSaisi, Date laDateModif) {
		this.id = id;
		this.pharmAssurance = pharmAssurance;
		this.pharmClient = pharmClient;
		this.laNumAssur = laNumAssur;
		this.laTaux = laTaux;
		this.laDateSaisi = laDateSaisi;
		this.laDateModif = laDateModif;
	}

	public PharmLigneAssuranceId getId() {
		return this.id;
	}

	public void setId(PharmLigneAssuranceId id) {
		this.id = id;
	}

	public PharmAssurance getPharmAssurance() {
		return this.pharmAssurance;
	}

	public void setPharmAssurance(PharmAssurance pharmAssurance) {
		this.pharmAssurance = pharmAssurance;
	}

	public PharmClient getPharmClient() {
		return this.pharmClient;
	}

	public void setPharmClient(PharmClient pharmClient) {
		this.pharmClient = pharmClient;
	}

	public String getLaNumAssur() {
		return this.laNumAssur;
	}

	public void setLaNumAssur(String laNumAssur) {
		this.laNumAssur = laNumAssur;
	}

	public Integer getLaTaux() {
		return this.laTaux;
	}

	public void setLaTaux(Integer laTaux) {
		this.laTaux = laTaux;
	}

	public Date getLaDateSaisi() {
		return this.laDateSaisi;
	}

	public void setLaDateSaisi(Date laDateSaisi) {
		this.laDateSaisi = laDateSaisi;
	}

	public Date getLaDateModif() {
		return this.laDateModif;
	}

	public void setLaDateModif(Date laDateModif) {
		this.laDateModif = laDateModif;
	}

}
