package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PharmRegime generated by hbm2java
 */
public class PharmRegime implements java.io.Serializable {

	private Integer regimId;
	private PharmProgramme pharmProgramme;
	private String regimLib;
	private Set<PharmProduit> pharmProduits = new HashSet<PharmProduit>(0);
	private Set<PharmOrdonnance> pharmOrdonnances = new HashSet<PharmOrdonnance>(
			0);

	public PharmRegime() {
	}

	public PharmRegime(PharmProgramme pharmProgramme, String regimLib,
			Set<PharmProduit> pharmProduits,
			Set<PharmOrdonnance> pharmOrdonnances) {
		this.pharmProgramme = pharmProgramme;
		this.regimLib = regimLib;
		this.pharmProduits = pharmProduits;
		this.pharmOrdonnances = pharmOrdonnances;
	}

	public Integer getRegimId() {
		return this.regimId;
	}

	public void setRegimId(Integer regimId) {
		this.regimId = regimId;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public String getRegimLib() {
		return this.regimLib;
	}

	public void setRegimLib(String regimLib) {
		this.regimLib = regimLib;
	}

	public Set<PharmProduit> getPharmProduits() {
		return this.pharmProduits;
	}

	public void setPharmProduits(Set<PharmProduit> pharmProduits) {
		this.pharmProduits = pharmProduits;
	}

	public Set<PharmOrdonnance> getPharmOrdonnances() {
		return this.pharmOrdonnances;
	}

	public void setPharmOrdonnances(Set<PharmOrdonnance> pharmOrdonnances) {
		this.pharmOrdonnances = pharmOrdonnances;
	}

}
