package org.openmrs.module.pharmagest;
// Generated 3 févr. 2016 16:54:55 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneCommandeSiteId generated by hbm2java
 */
public class PharmLigneCommandeSiteId implements java.io.Serializable {

	private int prodId;
	private int comSiteId;

	public PharmLigneCommandeSiteId() {
	}

	public PharmLigneCommandeSiteId(int prodId, int comSiteId) {
		this.prodId = prodId;
		this.comSiteId = comSiteId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public int getComSiteId() {
		return this.comSiteId;
	}

	public void setComSiteId(int comSiteId) {
		this.comSiteId = comSiteId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmLigneCommandeSiteId))
			return false;
		PharmLigneCommandeSiteId castOther = (PharmLigneCommandeSiteId) other;

		return (this.getProdId() == castOther.getProdId()) && (this.getComSiteId() == castOther.getComSiteId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProdId();
		result = 37 * result + this.getComSiteId();
		return result;
	}

}
