package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

/**
 * PharmLigneDispensationId generated by hbm2java
 */
public class PharmLigneDispensationId implements java.io.Serializable {

	private int ordId;
	private int prodId;

	public PharmLigneDispensationId() {
	}

	public PharmLigneDispensationId(int ordId, int prodId) {
		this.ordId = ordId;
		this.prodId = prodId;
	}

	public int getOrdId() {
		return this.ordId;
	}

	public void setOrdId(int ordId) {
		this.ordId = ordId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmLigneDispensationId))
			return false;
		PharmLigneDispensationId castOther = (PharmLigneDispensationId) other;

		return (this.getOrdId() == castOther.getOrdId())
				&& (this.getProdId() == castOther.getProdId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrdId();
		result = 37 * result + this.getProdId();
		return result;
	}

}
