package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

/**
 * PharmLigneDispensation generated by hbm2java
 */
public class PharmLigneDispensation implements java.io.Serializable {

	private PharmLigneDispensationId id;
	private PharmOrdonnance pharmOrdonnance;
	private PharmProduit pharmProduit;
	private Integer ldQteDem;
	private Integer ldQteServi;
	private Integer ldPrixUnit;

	public PharmLigneDispensation() {
	}

	public PharmLigneDispensation(PharmLigneDispensationId id,
			PharmOrdonnance pharmOrdonnance, PharmProduit pharmProduit) {
		this.id = id;
		this.pharmOrdonnance = pharmOrdonnance;
		this.pharmProduit = pharmProduit;
	}

	public PharmLigneDispensation(PharmLigneDispensationId id,
			PharmOrdonnance pharmOrdonnance, PharmProduit pharmProduit,
			Integer ldQteDem, Integer ldQteServi, Integer ldPrixUnit) {
		this.id = id;
		this.pharmOrdonnance = pharmOrdonnance;
		this.pharmProduit = pharmProduit;
		this.ldQteDem = ldQteDem;
		this.ldQteServi = ldQteServi;
		this.ldPrixUnit = ldPrixUnit;
	}

	public PharmLigneDispensationId getId() {
		return this.id;
	}

	public void setId(PharmLigneDispensationId id) {
		this.id = id;
	}

	public PharmOrdonnance getPharmOrdonnance() {
		return this.pharmOrdonnance;
	}

	public void setPharmOrdonnance(PharmOrdonnance pharmOrdonnance) {
		this.pharmOrdonnance = pharmOrdonnance;
	}

	public PharmProduit getPharmProduit() {
		return this.pharmProduit;
	}

	public void setPharmProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public Integer getLdQteDem() {
		return this.ldQteDem;
	}

	public void setLdQteDem(Integer ldQteDem) {
		this.ldQteDem = ldQteDem;
	}

	public Integer getLdQteServi() {
		return this.ldQteServi;
	}

	public void setLdQteServi(Integer ldQteServi) {
		this.ldQteServi = ldQteServi;
	}

	public Integer getLdPrixUnit() {
		return this.ldPrixUnit;
	}

	public void setLdPrixUnit(Integer ldPrixUnit) {
		this.ldPrixUnit = ldPrixUnit;
	}

}
