package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmOperation generated by hbm2java
 */
public class PharmOperation implements java.io.Serializable {

	private Integer operId;
	private PharmGestionnairePharma pharmGestionnairePharma;
	private PharmTypeOperation pharmTypeOperation;
	private PharmProgramme pharmProgramme;
	private PharmFournisseur pharmFournisseur;
	private String operNum;
	private Date operDateRecept;
	private Date operDateSaisi;
	private String operObserv;
	private String operRef;
	private Set<PharmLigneOperation> pharmLigneOperations = new HashSet<PharmLigneOperation>(
			0);

	public PharmOperation() {
	}

	public PharmOperation(PharmGestionnairePharma pharmGestionnairePharma,
			PharmTypeOperation pharmTypeOperation) {
		this.pharmGestionnairePharma = pharmGestionnairePharma;
		this.pharmTypeOperation = pharmTypeOperation;
	}

	public PharmOperation(PharmGestionnairePharma pharmGestionnairePharma,
			PharmTypeOperation pharmTypeOperation,
			PharmProgramme pharmProgramme, PharmFournisseur pharmFournisseur,
			String operNum, Date operDateRecept, Date operDateSaisi,
			String operObserv, String operRef,
			Set<PharmLigneOperation> pharmLigneOperations) {
		this.pharmGestionnairePharma = pharmGestionnairePharma;
		this.pharmTypeOperation = pharmTypeOperation;
		this.pharmProgramme = pharmProgramme;
		this.pharmFournisseur = pharmFournisseur;
		this.operNum = operNum;
		this.operDateRecept = operDateRecept;
		this.operDateSaisi = operDateSaisi;
		this.operObserv = operObserv;
		this.operRef = operRef;
		this.pharmLigneOperations = pharmLigneOperations;
	}

	public Integer getOperId() {
		return this.operId;
	}

	public void setOperId(Integer operId) {
		this.operId = operId;
	}

	public PharmGestionnairePharma getPharmGestionnairePharma() {
		return this.pharmGestionnairePharma;
	}

	public void setPharmGestionnairePharma(
			PharmGestionnairePharma pharmGestionnairePharma) {
		this.pharmGestionnairePharma = pharmGestionnairePharma;
	}

	public PharmTypeOperation getPharmTypeOperation() {
		return this.pharmTypeOperation;
	}

	public void setPharmTypeOperation(PharmTypeOperation pharmTypeOperation) {
		this.pharmTypeOperation = pharmTypeOperation;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public PharmFournisseur getPharmFournisseur() {
		return this.pharmFournisseur;
	}

	public void setPharmFournisseur(PharmFournisseur pharmFournisseur) {
		this.pharmFournisseur = pharmFournisseur;
	}

	public String getOperNum() {
		return this.operNum;
	}

	public void setOperNum(String operNum) {
		this.operNum = operNum;
	}

	public Date getOperDateRecept() {
		return this.operDateRecept;
	}

	public void setOperDateRecept(Date operDateRecept) {
		this.operDateRecept = operDateRecept;
	}

	public Date getOperDateSaisi() {
		return this.operDateSaisi;
	}

	public void setOperDateSaisi(Date operDateSaisi) {
		this.operDateSaisi = operDateSaisi;
	}

	public String getOperObserv() {
		return this.operObserv;
	}

	public void setOperObserv(String operObserv) {
		this.operObserv = operObserv;
	}

	public String getOperRef() {
		return this.operRef;
	}

	public void setOperRef(String operRef) {
		this.operRef = operRef;
	}

	public Set<PharmLigneOperation> getPharmLigneOperations() {
		return this.pharmLigneOperations;
	}

	public void setPharmLigneOperations(
			Set<PharmLigneOperation> pharmLigneOperations) {
		this.pharmLigneOperations = pharmLigneOperations;
	}

}
