package org.openmrs.module.pharmagest;
// Generated 18 janv. 2016 14:23:09 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmRapportCommande generated by hbm2java
 */
public class PharmRapportCommande implements java.io.Serializable {

	private Integer rapComId;
	private PharmProgramme pharmProgramme;
	private String rapComCode;
	private Date rapComDateCom;
	private String rapComPeriodLib;
	private Date rapComPeriodDate;
	private Integer rapComFalg;
	private Integer rapComStockMax;
	private Date rapComDateSaisi;
	private Date rapComDateModif;
	private Set<PharmLigneRc> pharmLigneRcs = new HashSet<PharmLigneRc>(0);

	public PharmRapportCommande() {
	}

	public PharmRapportCommande(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public PharmRapportCommande(PharmProgramme pharmProgramme, String rapComCode, Date rapComDateCom,
			String rapComPeriodLib, Date rapComPeriodDate, Integer rapComFalg, Integer rapComStockMax,
			Date rapComDateSaisi, Date rapComDateModif, Set<PharmLigneRc> pharmLigneRcs) {
		this.pharmProgramme = pharmProgramme;
		this.rapComCode = rapComCode;
		this.rapComDateCom = rapComDateCom;
		this.rapComPeriodLib = rapComPeriodLib;
		this.rapComPeriodDate = rapComPeriodDate;
		this.rapComFalg = rapComFalg;
		this.rapComStockMax = rapComStockMax;
		this.rapComDateSaisi = rapComDateSaisi;
		this.rapComDateModif = rapComDateModif;
		this.pharmLigneRcs = pharmLigneRcs;
	}

	public Integer getRapComId() {
		return this.rapComId;
	}

	public void setRapComId(Integer rapComId) {
		this.rapComId = rapComId;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public String getRapComCode() {
		return this.rapComCode;
	}

	public void setRapComCode(String rapComCode) {
		this.rapComCode = rapComCode;
	}

	public Date getRapComDateCom() {
		return this.rapComDateCom;
	}

	public void setRapComDateCom(Date rapComDateCom) {
		this.rapComDateCom = rapComDateCom;
	}

	public String getRapComPeriodLib() {
		return this.rapComPeriodLib;
	}

	public void setRapComPeriodLib(String rapComPeriodLib) {
		this.rapComPeriodLib = rapComPeriodLib;
	}

	public Date getRapComPeriodDate() {
		return this.rapComPeriodDate;
	}

	public void setRapComPeriodDate(Date rapComPeriodDate) {
		this.rapComPeriodDate = rapComPeriodDate;
	}

	public Integer getRapComFalg() {
		return this.rapComFalg;
	}

	public void setRapComFalg(Integer rapComFalg) {
		this.rapComFalg = rapComFalg;
	}

	public Integer getRapComStockMax() {
		return this.rapComStockMax;
	}

	public void setRapComStockMax(Integer rapComStockMax) {
		this.rapComStockMax = rapComStockMax;
	}

	public Date getRapComDateSaisi() {
		return this.rapComDateSaisi;
	}

	public void setRapComDateSaisi(Date rapComDateSaisi) {
		this.rapComDateSaisi = rapComDateSaisi;
	}

	public Date getRapComDateModif() {
		return this.rapComDateModif;
	}

	public void setRapComDateModif(Date rapComDateModif) {
		this.rapComDateModif = rapComDateModif;
	}

	public Set<PharmLigneRc> getPharmLigneRcs() {
		return this.pharmLigneRcs;
	}

	public void setPharmLigneRcs(Set<PharmLigneRc> pharmLigneRcs) {
		this.pharmLigneRcs = pharmLigneRcs;
	}

}
