package org.openmrs.module.pharmagest;
// Generated 3 févr. 2016 16:54:55 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneRcId generated by hbm2java
 */
public class PharmLigneRcId implements java.io.Serializable {

	private int prodId;
	private int rapComId;

	public PharmLigneRcId() {
	}

	public PharmLigneRcId(int prodId, int rapComId) {
		this.prodId = prodId;
		this.rapComId = rapComId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public int getRapComId() {
		return this.rapComId;
	}

	public void setRapComId(int rapComId) {
		this.rapComId = rapComId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmLigneRcId))
			return false;
		PharmLigneRcId castOther = (PharmLigneRcId) other;

		return (this.getProdId() == castOther.getProdId()) && (this.getRapComId() == castOther.getRapComId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProdId();
		result = 37 * result + this.getRapComId();
		return result;
	}

}
