package org.openmrs.module.pharmagest;

// Generated 16 ao�t 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmProduit generated by hbm2java
 */
public class PharmProduit implements java.io.Serializable {

	private Integer prodId;
	private PharmClassePharma pharmClassePharma;
	private String prodLib;
	private String prodCode;
	private Date prodDateExp;
	private Set<PharmRegime> pharmRegimes = new HashSet<PharmRegime>(0);
	private Set<PharmPrixProduit> pharmPrixProduits = new HashSet<PharmPrixProduit>(0);
	private Set<PharmLigneDispensation> pharmLigneDispensations = new HashSet<PharmLigneDispensation>(0);
	private Set<PharmHistoMouvementStock> pharmHistoMouvementStocks = new HashSet<PharmHistoMouvementStock>(0);
	private Set<PharmProduitAttribut> pharmProduitAttributs = new HashSet<PharmProduitAttribut>(0);
	private Set<PharmProgramme> pharmProgrammes = new HashSet<PharmProgramme>(0);

	public PharmProduit() {
	}

	public PharmProduit(PharmClassePharma pharmClassePharma, String prodLib, Date prodDateExp,
			Set<PharmRegime> pharmRegimes, Set<PharmPrixProduit> pharmPrixProduits,
			Set<PharmLigneDispensation> pharmLigneDispensations,
			Set<PharmHistoMouvementStock> pharmHistoMouvementStocks, Set<PharmProduitAttribut> pharmProduitAttributs,
			Set<PharmProgramme> pharmProgrammes) {
		this.pharmClassePharma = pharmClassePharma;
		this.prodLib = prodLib;
		this.prodDateExp = prodDateExp;
		this.pharmRegimes = pharmRegimes;
		this.pharmPrixProduits = pharmPrixProduits;
		this.pharmLigneDispensations = pharmLigneDispensations;
		this.pharmHistoMouvementStocks = pharmHistoMouvementStocks;
		this.pharmProduitAttributs = pharmProduitAttributs;
		this.pharmProgrammes = pharmProgrammes;
	}

	public Integer getProdId() {
		return this.prodId;
	}

	public void setProdId(Integer prodId) {
		this.prodId = prodId;
	}

	public PharmClassePharma getPharmClassePharma() {
		return this.pharmClassePharma;
	}

	public void setPharmClassePharma(PharmClassePharma pharmClassePharma) {
		this.pharmClassePharma = pharmClassePharma;
	}

	public String getProdLib() {
		return this.prodLib;
	}

	public void setProdLib(String prodLib) {
		this.prodLib = prodLib;
	}

	public Date getProdDateExp() {
		return this.prodDateExp;
	}

	public void setProdDateExp(Date prodDateExp) {
		this.prodDateExp = prodDateExp;
	}

	public String getProdCode() {
		return prodCode;
	}

	public void setProdCode(String prodCode) {
		this.prodCode = prodCode;
	}

	public Set<PharmRegime> getPharmRegimes() {
		return this.pharmRegimes;
	}

	public void setPharmRegimes(Set<PharmRegime> pharmRegimes) {
		this.pharmRegimes = pharmRegimes;
	}

	public Set<PharmPrixProduit> getPharmPrixProduits() {
		return this.pharmPrixProduits;
	}

	public void setPharmPrixProduits(Set<PharmPrixProduit> pharmPrixProduits) {
		this.pharmPrixProduits = pharmPrixProduits;
	}

	public Set<PharmLigneDispensation> getPharmLigneDispensations() {
		return this.pharmLigneDispensations;
	}

	public void setPharmLigneDispensations(Set<PharmLigneDispensation> pharmLigneDispensations) {
		this.pharmLigneDispensations = pharmLigneDispensations;
	}

	public Set<PharmHistoMouvementStock> getPharmHistoMouvementStocks() {
		return this.pharmHistoMouvementStocks;
	}

	public void setPharmHistoMouvementStocks(Set<PharmHistoMouvementStock> pharmHistoMouvementStocks) {
		this.pharmHistoMouvementStocks = pharmHistoMouvementStocks;
	}

	public Set<PharmProduitAttribut> getPharmProduitAttributs() {
		return this.pharmProduitAttributs;
	}

	public void setPharmProduitAttributs(Set<PharmProduitAttribut> pharmProduitAttributs) {
		this.pharmProduitAttributs = pharmProduitAttributs;
	}

	public Set<PharmProgramme> getPharmProgrammes() {
		return this.pharmProgrammes;
	}

	public void setPharmProgrammes(Set<PharmProgramme> pharmProgrammes) {
		this.pharmProgrammes = pharmProgrammes;
	}

	public String getFullName() {
		return this.getProdCode()+" - "+this.getProdLib();
	}


}
