package org.openmrs.module.pharmagest;
// Generated 18 janv. 2016 14:23:09 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmCommandeSite generated by hbm2java
 */
public class PharmCommandeSite implements java.io.Serializable {

	private Integer comSiteId;
	private PharmProgramme pharmProgramme;
	private PharmSite pharmSite;
	private String comSiteCode;
	private Date comSiteDateCom;
	private String comSitePeriodLib;
	private Date comSitePeriodDate;
	private Integer comSiteFlag;
	private Integer comStockMax;
	private Date comSiteDateSaisi;
	private Date comSiteDateModif;
	private Set<PharmLigneCommandeSite> pharmLigneCommandeSites = new HashSet<PharmLigneCommandeSite>(0);

	public PharmCommandeSite() {
	}

	public PharmCommandeSite(PharmProgramme pharmProgramme, PharmSite pharmSite) {
		this.pharmProgramme = pharmProgramme;
		this.pharmSite = pharmSite;
	}

	public PharmCommandeSite(PharmProgramme pharmProgramme, PharmSite pharmSite, String comSiteCode,
			Date comSiteDateCom, String comSitePeriodLib, Date comSitePeriodDate, Integer comSiteFlag, Integer comStockMax,
			Date comSiteDateSaisi, Date comSiteDateModif, Set<PharmLigneCommandeSite> pharmLigneCommandeSites) {
		this.pharmProgramme = pharmProgramme;
		this.pharmSite = pharmSite;
		this.comSiteCode = comSiteCode;
		this.comSiteDateCom = comSiteDateCom;
		this.comSitePeriodLib = comSitePeriodLib;
		this.comSitePeriodDate = comSitePeriodDate;
		this.setComSiteFlag(comSiteFlag);
		this.comStockMax = comStockMax;
		this.comSiteDateSaisi = comSiteDateSaisi;
		this.comSiteDateModif = comSiteDateModif;
		this.pharmLigneCommandeSites = pharmLigneCommandeSites;
	}

	public Integer getComSiteId() {
		return this.comSiteId;
	}

	public void setComSiteId(Integer comSiteId) {
		this.comSiteId = comSiteId;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public PharmSite getPharmSite() {
		return this.pharmSite;
	}

	public void setPharmSite(PharmSite pharmSite) {
		this.pharmSite = pharmSite;
	}

	public String getComSiteCode() {
		return this.comSiteCode;
	}

	public void setComSiteCode(String comSiteCode) {
		this.comSiteCode = comSiteCode;
	}

	public Date getComSiteDateCom() {
		return this.comSiteDateCom;
	}

	public void setComSiteDateCom(Date comSiteDateCom) {
		this.comSiteDateCom = comSiteDateCom;
	}

	public String getComSitePeriodLib() {
		return this.comSitePeriodLib;
	}

	public void setComSitePeriodLib(String comSitePeriodLib) {
		this.comSitePeriodLib = comSitePeriodLib;
	}

	public Date getComSitePeriodDate() {
		return this.comSitePeriodDate;
	}

	public void setComSitePeriodDate(Date comSitePeriodDate) {
		this.comSitePeriodDate = comSitePeriodDate;
	}



	public Integer getComStockMax() {
		return this.comStockMax;
	}

	public void setComStockMax(Integer comStockMax) {
		this.comStockMax = comStockMax;
	}

	public Date getComSiteDateSaisi() {
		return this.comSiteDateSaisi;
	}

	public void setComSiteDateSaisi(Date comSiteDateSaisi) {
		this.comSiteDateSaisi = comSiteDateSaisi;
	}

	public Date getComSiteDateModif() {
		return this.comSiteDateModif;
	}

	public void setComSiteDateModif(Date comSiteDateModif) {
		this.comSiteDateModif = comSiteDateModif;
	}

	public Set<PharmLigneCommandeSite> getPharmLigneCommandeSites() {
		return this.pharmLigneCommandeSites;
	}

	public void setPharmLigneCommandeSites(Set<PharmLigneCommandeSite> pharmLigneCommandeSites) {
		this.pharmLigneCommandeSites = pharmLigneCommandeSites;
	}

	public Integer getComSiteFlag() {
		return comSiteFlag;
	}

	public void setComSiteFlag(Integer comSiteFlag) {
		this.comSiteFlag = comSiteFlag;
	}

}
