package org.openmrs.module.pharmagest;

// Generated 16 ao�t 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmInventaire generated by hbm2java
 */
public class PharmInventaire implements java.io.Serializable {

	private Integer invId;
	private PharmProgramme pharmProgramme;
	private Date invDateCrea;
	private Date invDeb;
	private Date invFin;
	private String invFlag;
	private Date invDateModif;
	private PharmGestionnairePharma pharmGestionnaireSaisi;
	private PharmGestionnairePharma pharmGestionnaireModif;
	
	private Set<PharmLigneInventaire> pharmLigneInventaires = new HashSet<PharmLigneInventaire>(0);

	public PharmInventaire() {
	}

	public PharmInventaire(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public PharmInventaire(PharmProgramme pharmProgramme, Date invDateCrea, Date invDeb, Date invFin, String invFlag,
			Set<PharmLigneInventaire> pharmLigneInventaires) {
		this.pharmProgramme = pharmProgramme;
		this.invDateCrea = invDateCrea;
		this.invDeb = invDeb;
		this.invFin = invFin;
		this.invFlag = invFlag;
		this.pharmLigneInventaires = pharmLigneInventaires;
	}

	public Integer getInvId() {
		return this.invId;
	}

	public void setInvId(Integer invId) {
		this.invId = invId;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public Date getInvDateCrea() {
		return this.invDateCrea;
	}

	public void setInvDateCrea(Date invDateCrea) {
		this.invDateCrea = invDateCrea;
	}

	public Date getInvDeb() {
		return this.invDeb;
	}

	public void setInvDeb(Date invDeb) {
		this.invDeb = invDeb;
	}

	public Date getInvFin() {
		return this.invFin;
	}

	public void setInvFin(Date invFin) {
		this.invFin = invFin;
	}

	public String getInvFlag() {
		return this.invFlag;
	}

	public void setInvFlag(String invFlag) {
		this.invFlag = invFlag;
	}

	public Date getInvDateModif() {
		return invDateModif;
	}

	public void setInvDateModif(Date invDateModif) {
		this.invDateModif = invDateModif;
	}

	public PharmGestionnairePharma getPharmGestionnaireSaisi() {
		return pharmGestionnaireSaisi;
	}

	public void setPharmGestionnaireSaisi(PharmGestionnairePharma pharmGestionnaireSaisi) {
		this.pharmGestionnaireSaisi = pharmGestionnaireSaisi;
	}

	public PharmGestionnairePharma getPharmGestionnaireModif() {
		return pharmGestionnaireModif;
	}

	public void setPharmGestionnaireModif(PharmGestionnairePharma pharmGestionnaireModif) {
		this.pharmGestionnaireModif = pharmGestionnaireModif;
	}

	public Set<PharmLigneInventaire> getPharmLigneInventaires() {
		return this.pharmLigneInventaires;
	}

	public void setPharmLigneInventaires(Set<PharmLigneInventaire> pharmLigneInventaires) {
		this.pharmLigneInventaires = pharmLigneInventaires;
	}

}
