package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PharmProgramme generated by hbm2java
 */
public class PharmProgramme implements java.io.Serializable {

	private Integer programId;
	private String programLib;
	private Set<PharmOrdonnance> pharmOrdonnances = new HashSet<PharmOrdonnance>(
			0);
	private Set<PharmRegime> pharmRegimes = new HashSet<PharmRegime>(0);
	private Set<PharmStocker> pharmStockers = new HashSet<PharmStocker>(0);
	private Set<PharmProduit> pharmProduits = new HashSet<PharmProduit>(0);
	private Set<PharmOperation> pharmOperations = new HashSet<PharmOperation>(0);
	private Set<PharmLigneInventaire> pharmLigneInventaires = new HashSet<PharmLigneInventaire>(
			0);

	public PharmProgramme() {
	}

	public PharmProgramme(String programLib,
			Set<PharmOrdonnance> pharmOrdonnances,
			Set<PharmRegime> pharmRegimes, Set<PharmStocker> pharmStockers,
			Set<PharmProduit> pharmProduits,
			Set<PharmOperation> pharmOperations,
			Set<PharmLigneInventaire> pharmLigneInventaires) {
		this.programLib = programLib;
		this.pharmOrdonnances = pharmOrdonnances;
		this.pharmRegimes = pharmRegimes;
		this.pharmStockers = pharmStockers;
		this.pharmProduits = pharmProduits;
		this.pharmOperations = pharmOperations;
		this.pharmLigneInventaires = pharmLigneInventaires;
	}

	public Integer getProgramId() {
		return this.programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

	public String getProgramLib() {
		return this.programLib;
	}

	public void setProgramLib(String programLib) {
		this.programLib = programLib;
	}

	public Set<PharmOrdonnance> getPharmOrdonnances() {
		return this.pharmOrdonnances;
	}

	public void setPharmOrdonnances(Set<PharmOrdonnance> pharmOrdonnances) {
		this.pharmOrdonnances = pharmOrdonnances;
	}

	public Set<PharmRegime> getPharmRegimes() {
		return this.pharmRegimes;
	}

	public void setPharmRegimes(Set<PharmRegime> pharmRegimes) {
		this.pharmRegimes = pharmRegimes;
	}

	public Set<PharmStocker> getPharmStockers() {
		return this.pharmStockers;
	}

	public void setPharmStockers(Set<PharmStocker> pharmStockers) {
		this.pharmStockers = pharmStockers;
	}

	public Set<PharmProduit> getPharmProduits() {
		return this.pharmProduits;
	}

	public void setPharmProduits(Set<PharmProduit> pharmProduits) {
		this.pharmProduits = pharmProduits;
	}

	public Set<PharmOperation> getPharmOperations() {
		return this.pharmOperations;
	}

	public void setPharmOperations(Set<PharmOperation> pharmOperations) {
		this.pharmOperations = pharmOperations;
	}

	public Set<PharmLigneInventaire> getPharmLigneInventaires() {
		return this.pharmLigneInventaires;
	}

	public void setPharmLigneInventaires(
			Set<PharmLigneInventaire> pharmLigneInventaires) {
		this.pharmLigneInventaires = pharmLigneInventaires;
	}

}
