package org.openmrs.module.pharmagest;
// Generated 16 mai 2017 05:51:27 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneReception generated by hbm2java
 */
public class PharmLigneReception implements java.io.Serializable {

	private PharmLigneReceptionId id;
	private PharmProduitAttribut pharmProduitAttribut;
	private PharmReception pharmReception;
	private Integer lgnRecptQteLivre;
	private Integer lgnRecptQteRecu;
	private Integer lgnRecptQteDetailLivre;
	private Integer lgnRecptQteDetailRecu;
	private Integer lgnRecptPrix;
	private Integer lgnRecptQteRef;
	private String lgnRecptObserv;

	public PharmLigneReception() {
	}

	public PharmLigneReception(PharmLigneReceptionId id, PharmProduitAttribut pharmProduitAttribut,
			PharmReception pharmReception) {
		this.id = id;
		this.pharmProduitAttribut = pharmProduitAttribut;
		this.pharmReception = pharmReception;
	}

	public PharmLigneReception(PharmLigneReceptionId id, PharmProduitAttribut pharmProduitAttribut,
			PharmReception pharmReception, Integer lgnRecptQteLivre, Integer lgnRecptQteRecu,
			Integer lgnRecptQteDetailLivre, Integer lgnRecptQteDetailRecu, Integer lgnRecptPrix, Integer lgnRecptQteRef,
			String lgnRecptObserv) {
		this.id = id;
		this.pharmProduitAttribut = pharmProduitAttribut;
		this.pharmReception = pharmReception;
		this.lgnRecptQteLivre = lgnRecptQteLivre;
		this.lgnRecptQteRecu = lgnRecptQteRecu;
		this.lgnRecptQteDetailLivre = lgnRecptQteDetailLivre;
		this.lgnRecptQteDetailRecu = lgnRecptQteDetailRecu;
		this.lgnRecptPrix = lgnRecptPrix;
		this.lgnRecptQteRef = lgnRecptQteRef;
		this.lgnRecptObserv = lgnRecptObserv;
	}

	public PharmLigneReceptionId getId() {
		return this.id;
	}

	public void setId(PharmLigneReceptionId id) {
		this.id = id;
	}

	public PharmProduitAttribut getPharmProduitAttribut() {
		return this.pharmProduitAttribut;
	}

	public void setPharmProduitAttribut(PharmProduitAttribut pharmProduitAttribut) {
		this.pharmProduitAttribut = pharmProduitAttribut;
	}

	public PharmReception getPharmReception() {
		return this.pharmReception;
	}

	public void setPharmReception(PharmReception pharmReception) {
		this.pharmReception = pharmReception;
	}

	public Integer getLgnRecptQteLivre() {
		return this.lgnRecptQteLivre;
	}

	public void setLgnRecptQteLivre(Integer lgnRecptQteLivre) {
		this.lgnRecptQteLivre = lgnRecptQteLivre;
	}

	public Integer getLgnRecptQteRecu() {
		return this.lgnRecptQteRecu;
	}

	public void setLgnRecptQteRecu(Integer lgnRecptQteRecu) {
		this.lgnRecptQteRecu = lgnRecptQteRecu;
	}

	public Integer getLgnRecptQteDetailLivre() {
		return this.lgnRecptQteDetailLivre;
	}

	public void setLgnRecptQteDetailLivre(Integer lgnRecptQteDetailLivre) {
		this.lgnRecptQteDetailLivre = lgnRecptQteDetailLivre;
	}

	public Integer getLgnRecptQteDetailRecu() {
		return this.lgnRecptQteDetailRecu;
	}

	public void setLgnRecptQteDetailRecu(Integer lgnRecptQteDetailRecu) {
		this.lgnRecptQteDetailRecu = lgnRecptQteDetailRecu;
	}

	public Integer getLgnRecptPrix() {
		return this.lgnRecptPrix;
	}

	public void setLgnRecptPrix(Integer lgnRecptPrix) {
		this.lgnRecptPrix = lgnRecptPrix;
	}

	public Integer getLgnRecptQteRef() {
		return this.lgnRecptQteRef;
	}

	public void setLgnRecptQteRef(Integer lgnRecptQteRef) {
		this.lgnRecptQteRef = lgnRecptQteRef;
	}

	public String getLgnRecptObserv() {
		return this.lgnRecptObserv;
	}

	public void setLgnRecptObserv(String lgnRecptObserv) {
		this.lgnRecptObserv = lgnRecptObserv;
	}

}
