package org.openmrs.module.pharmagest;
// Generated 16 mai 2017 05:51:27 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmReception generated by hbm2java
 */
public class PharmReception implements java.io.Serializable {

	private Integer recptId;
	private PharmTypeOperation pharmTypeOperation;
	private PharmFournisseur pharmFournisseur;
	private PharmGestionnairePharma pharmGestionnairePharma;
	private PharmGestionnairePharma pharmGestionnaireModif;
	private PharmProgramme pharmProgramme;
	private String recptNum;
	private Date recptDateRecept;
	private Date recptDateSaisi;
	private Date recptDateModif;
	private String recptFlag;
	private String recptRef;
	private String recptObserv;
	private String typeReception;
	private Set<PharmLigneReception> pharmLigneReceptions = new HashSet<PharmLigneReception>(0);

	public PharmReception() {
	}

	public PharmReception(PharmFournisseur pharmFournisseur, PharmGestionnairePharma pharmGestionnairePharma,
			PharmProgramme pharmProgramme) {
		this.pharmFournisseur = pharmFournisseur;
		this.pharmGestionnairePharma = pharmGestionnairePharma;
		this.pharmProgramme = pharmProgramme;
	}

	public PharmReception(PharmTypeOperation pharmTypeOperation, PharmFournisseur pharmFournisseur,
			PharmGestionnairePharma pharmGestionnairePharma, PharmProgramme pharmProgramme, String recptNum,
			Date recptDateRecept, Date recptDateSaisi, Date recptDateModif, String recptFlag, String recptRef,
			String recptObserv, Set<PharmLigneReception> pharmLigneReceptions) {
		this.pharmTypeOperation = pharmTypeOperation;
		this.pharmFournisseur = pharmFournisseur;
		this.pharmGestionnairePharma = pharmGestionnairePharma;
		this.pharmProgramme = pharmProgramme;
		this.recptNum = recptNum;
		this.recptDateRecept = recptDateRecept;
		this.recptDateSaisi = recptDateSaisi;
		this.recptDateModif = recptDateModif;
		this.recptFlag = recptFlag;
		this.recptRef = recptRef;
		this.recptObserv = recptObserv;
		this.pharmLigneReceptions = pharmLigneReceptions;
	}

	public Integer getRecptId() {
		return this.recptId;
	}

	public void setRecptId(Integer recptId) {
		this.recptId = recptId;
	}

	public PharmTypeOperation getPharmTypeOperation() {
		return this.pharmTypeOperation;
	}

	public void setPharmTypeOperation(PharmTypeOperation pharmTypeOperation) {
		this.pharmTypeOperation = pharmTypeOperation;
	}

	public PharmFournisseur getPharmFournisseur() {
		return this.pharmFournisseur;
	}

	public void setPharmFournisseur(PharmFournisseur pharmFournisseur) {
		this.pharmFournisseur = pharmFournisseur;
	}

	public PharmGestionnairePharma getPharmGestionnairePharma() {
		return this.pharmGestionnairePharma;
	}

	public void setPharmGestionnairePharma(PharmGestionnairePharma pharmGestionnairePharma) {
		this.pharmGestionnairePharma = pharmGestionnairePharma;
	}

	public PharmGestionnairePharma getPharmGestionnaireModif() {
		return pharmGestionnaireModif;
	}

	public void setPharmGestionnaireModif(PharmGestionnairePharma pharmGestionnaireModif) {
		this.pharmGestionnaireModif = pharmGestionnaireModif;
	}

	public PharmProgramme getPharmProgramme() {
		return this.pharmProgramme;
	}

	public void setPharmProgramme(PharmProgramme pharmProgramme) {
		this.pharmProgramme = pharmProgramme;
	}

	public String getRecptNum() {
		return this.recptNum;
	}

	public void setRecptNum(String recptNum) {
		this.recptNum = recptNum;
	}

	public Date getRecptDateRecept() {
		return this.recptDateRecept;
	}

	public void setRecptDateRecept(Date recptDateRecept) {
		this.recptDateRecept = recptDateRecept;
	}

	public Date getRecptDateSaisi() {
		return this.recptDateSaisi;
	}

	public void setRecptDateSaisi(Date recptDateSaisi) {
		this.recptDateSaisi = recptDateSaisi;
	}

	public Date getRecptDateModif() {
		return this.recptDateModif;
	}

	public void setRecptDateModif(Date recptDateModif) {
		this.recptDateModif = recptDateModif;
	}

	public String getRecptFlag() {
		return this.recptFlag;
	}

	public void setRecptFlag(String recptFlag) {
		this.recptFlag = recptFlag;
	}

	public String getRecptRef() {
		return this.recptRef;
	}

	public void setRecptRef(String recptRef) {
		this.recptRef = recptRef;
	}

	public String getRecptObserv() {
		return this.recptObserv;
	}

	public void setRecptObserv(String recptObserv) {
		this.recptObserv = recptObserv;
	}

	public Set<PharmLigneReception> getPharmLigneReceptions() {
		return this.pharmLigneReceptions;
	}

	public void setPharmLigneReceptions(Set<PharmLigneReception> pharmLigneReceptions) {
		this.pharmLigneReceptions = pharmLigneReceptions;
	}

	public String getTypeReception() {
		return typeReception;
	}

	public void setTypeReception(String typeReception) {
		this.typeReception = typeReception;
	}

}
