package org.openmrs.module.pharmagest;

// Generated 16 ao�t 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PharmPrixProduit generated by hbm2java
 */
public class PharmPrixProduit implements java.io.Serializable {

	private Integer prixId;
	private PharmProduit pharmProduit;
	private Integer prixAchat;
	private Integer prixVente;
	private Date prixDateEff;
	private Boolean prixFlagActif;
	private Integer programId;

	public PharmPrixProduit() {
	}

	public PharmPrixProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public PharmPrixProduit(PharmProduit pharmProduit, Integer prixAchat,
			Integer prixVente, Date prixDateEff, Boolean prixFlagActif) {
		this.pharmProduit = pharmProduit;
		this.prixAchat = prixAchat;
		this.prixVente = prixVente;
		this.prixDateEff = prixDateEff;
		this.prixFlagActif = prixFlagActif;
	}

	public Integer getPrixId() {
		return this.prixId;
	}

	public void setPrixId(Integer prixId) {
		this.prixId = prixId;
	}

	public PharmProduit getPharmProduit() {
		return this.pharmProduit;
	}

	public void setPharmProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public Integer getPrixAchat() {
		return this.prixAchat;
	}

	public void setPrixAchat(Integer prixAchat) {
		this.prixAchat = prixAchat;
	}

	public Integer getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(Integer prixVente) {
		this.prixVente = prixVente;
	}

	public Date getPrixDateEff() {
		return this.prixDateEff;
	}

	public void setPrixDateEff(Date prixDateEff) {
		this.prixDateEff = prixDateEff;
	}

	public Boolean getPrixFlagActif() {
		return this.prixFlagActif;
	}

	public void setPrixFlagActif(Boolean prixFlagActif) {
		this.prixFlagActif = prixFlagActif;
	}

	public Integer getProgramId() {
		return programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

}
