package org.openmrs.module.pharmagest;
// Generated 3 f�vr. 2016 16:54:55 by Hibernate Tools 3.5.0.Final

/**
 * PharmLigneCommandeSite generated by hbm2java
 */
public class PharmLigneCommandeSite implements java.io.Serializable {

	private PharmLigneCommandeSiteId id;
	private PharmCommandeSite pharmCommandeSite;
	private PharmProduit pharmProduit;
	private Integer lgnComQteIni;
	private Integer lgnComQteRecu;
	private Integer lgnComQteUtil;
	private Integer lgnComPertes;
	private Integer lgnComStockDispo;
	private Integer lgnComNbreJrsRup;
	private Integer lgnQteDistriM1;
	private Integer lgnQteDistriM2;
	private Integer lgnQtePro;
	public PharmLigneCommandeSite() {
	}

	public PharmLigneCommandeSite(PharmLigneCommandeSiteId id, PharmCommandeSite pharmCommandeSite,
			PharmProduit pharmProduit) {
		this.id = id;
		this.pharmCommandeSite = pharmCommandeSite;
		this.pharmProduit = pharmProduit;
	}

	public PharmLigneCommandeSite(PharmLigneCommandeSiteId id, PharmCommandeSite pharmCommandeSite,
			PharmProduit pharmProduit, Integer lgnComQteIni, Integer lgnComQteRecu, Integer lgnComQteUtil,
			Integer lgnComPertes, Integer lgnComStockDispo, Integer lgnComNbreJrsRup, Integer lgnQteDistriM1,
			Integer lgnQteDistriM2) {
		this.id = id;
		this.pharmCommandeSite = pharmCommandeSite;
		this.pharmProduit = pharmProduit;
		this.lgnComQteIni = lgnComQteIni;
		this.lgnComQteRecu = lgnComQteRecu;
		this.lgnComQteUtil = lgnComQteUtil;
		this.lgnComPertes = lgnComPertes;
		this.lgnComStockDispo = lgnComStockDispo;
		this.lgnComNbreJrsRup = lgnComNbreJrsRup;
		this.lgnQteDistriM1 = lgnQteDistriM1;
		this.lgnQteDistriM2 = lgnQteDistriM2;
	}

	public PharmLigneCommandeSiteId getId() {
		return this.id;
	}

	public void setId(PharmLigneCommandeSiteId id) {
		this.id = id;
	}

	public PharmCommandeSite getPharmCommandeSite() {
		return this.pharmCommandeSite;
	}

	public void setPharmCommandeSite(PharmCommandeSite pharmCommandeSite) {
		this.pharmCommandeSite = pharmCommandeSite;
	}

	public PharmProduit getPharmProduit() {
		return this.pharmProduit;
	}

	public void setPharmProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public Integer getLgnComQteIni() {
		return this.lgnComQteIni;
	}

	public void setLgnComQteIni(Integer lgnComQteIni) {
		this.lgnComQteIni = lgnComQteIni;
	}

	public Integer getLgnComQteRecu() {
		return this.lgnComQteRecu;
	}

	public void setLgnComQteRecu(Integer lgnComQteRecu) {
		this.lgnComQteRecu = lgnComQteRecu;
	}

	public Integer getLgnComQteUtil() {
		return this.lgnComQteUtil;
	}

	public void setLgnComQteUtil(Integer lgnComQteUtil) {
		this.lgnComQteUtil = lgnComQteUtil;
	}

	public Integer getLgnComPertes() {
		return this.lgnComPertes;
	}

	public void setLgnComPertes(Integer lgnComPertes) {
		this.lgnComPertes = lgnComPertes;
	}

	public Integer getLgnComStockDispo() {
		return this.lgnComStockDispo;
	}

	public void setLgnComStockDispo(Integer lgnComStockDispo) {
		this.lgnComStockDispo = lgnComStockDispo;
	}

	public Integer getLgnComNbreJrsRup() {
		return this.lgnComNbreJrsRup;
	}

	public void setLgnComNbreJrsRup(Integer lgnComNbreJrsRup) {
		this.lgnComNbreJrsRup = lgnComNbreJrsRup;
	}

	public Integer getLgnQteDistriM1() {
		return this.lgnQteDistriM1;
	}

	public void setLgnQteDistriM1(Integer lgnQteDistriM1) {
		this.lgnQteDistriM1 = lgnQteDistriM1;
	}

	public Integer getLgnQteDistriM2() {
		return this.lgnQteDistriM2;
	}

	public void setLgnQteDistriM2(Integer lgnQteDistriM2) {
		this.lgnQteDistriM2 = lgnQteDistriM2;
	}

	public Integer getLgnQtePro() {
		return lgnQtePro;
	}

	public void setLgnQtePro(Integer lgnQtePro) {
		this.lgnQtePro = lgnQtePro;
	}

}
