package org.openmrs.module.pharmagest;
// Generated 17 mai 2017 11:20:09 by Hibernate Tools 3.5.0.Final

/**
 * PharmProduitCompl generated by hbm2java
 */
public class PharmProduitCompl implements java.io.Serializable, java.lang.Comparable {

	private int prodCplId;
	private PharmProduit pharmProduit;
	private String prodCplCode;
	private String prodCplLibGros;
	private String prodCplLibDetail;
	private String prodCplUnitGros;
	private String prodCplUnitDetail;
	private Integer prodCplUnitConvers;

	public PharmProduitCompl() {
	}

	public PharmProduitCompl(int prodCplId, PharmProduit pharmProduit) {
		this.prodCplId = prodCplId;
		this.pharmProduit = pharmProduit;
	}

	public PharmProduitCompl(int prodCplId, PharmProduit pharmProduit, String prodCplCode, String prodCplLibGros,
			String prodCplLibDetail, String prodCplUnitGros, String prodCplUnitDetail, Integer prodCplUnitConvers) {
		this.prodCplId = prodCplId;
		this.pharmProduit = pharmProduit;
		this.prodCplCode = prodCplCode;
		this.prodCplLibGros = prodCplLibGros;
		this.prodCplLibDetail = prodCplLibDetail;
		this.prodCplUnitGros = prodCplUnitGros;
		this.prodCplUnitDetail = prodCplUnitDetail;
		this.prodCplUnitConvers = prodCplUnitConvers;
	}

	public int getProdCplId() {
		return this.prodCplId;
	}

	public void setProdCplId(int prodCplId) {
		this.prodCplId = prodCplId;
	}

	public PharmProduit getPharmProduit() {
		return this.pharmProduit;
	}

	public void setPharmProduit(PharmProduit pharmProduit) {
		this.pharmProduit = pharmProduit;
	}

	public String getProdCplCode() {
		return this.prodCplCode;
	}

	public void setProdCplCode(String prodCplCode) {
		this.prodCplCode = prodCplCode;
	}

	public String getProdCplLibGros() {
		return this.prodCplLibGros;
	}

	public void setProdCplLibGros(String prodCplLibGros) {
		this.prodCplLibGros = prodCplLibGros;
	}

	public String getProdCplLibDetail() {
		return this.prodCplLibDetail;
	}

	public void setProdCplLibDetail(String prodCplLibDetail) {
		this.prodCplLibDetail = prodCplLibDetail;
	}

	public String getProdCplUnitGros() {
		return this.prodCplUnitGros;
	}

	public void setProdCplUnitGros(String prodCplUnitGros) {
		this.prodCplUnitGros = prodCplUnitGros;
	}

	public String getProdCplUnitDetail() {
		return this.prodCplUnitDetail;
	}

	public void setProdCplUnitDetail(String prodCplUnitDetail) {
		this.prodCplUnitDetail = prodCplUnitDetail;
	}

	public Integer getProdCplUnitConvers() {
		return this.prodCplUnitConvers;
	}

	public void setProdCplUnitConvers(Integer prodCplUnitConvers) {
		this.prodCplUnitConvers = prodCplUnitConvers;
	}
	
	public String getFullDetailName() {
		return this.getProdCplLibDetail() + " - " + this.getProdCplCode();
	}
	
	public String getFullGrosName() {
		return this.getProdCplLibGros() + " - " + this.getProdCplCode();
	}
	
	public int compareTo(Object o) {
		String s1 = ((PharmProduitCompl) o).getProdCplLibGros();
		String s2 = this.getProdCplLibGros();
		//System.out.println("s1.compareTo(s2) : "+s1.compareTo(s2));
		if (s1 != null && s2 != null) {
			if (s1.compareTo(s2) >= 1)
				return 1;
			else if (s1.compareTo(s2) <= -1)
				return -1;
			else if (s1.compareTo(s2) == 0)
				return 0;
			return 0;
		} else {
			return 0;
		}
	}

}
