package org.openmrs.module.pharmagest;

// Generated 16 ao�t 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

/**
 * PharmLigneInventaireId generated by hbm2java
 */
public class PharmLigneInventaireId implements java.io.Serializable {

	private int invId;
	private int prodAttriId;

	public PharmLigneInventaireId() {
	}

	public PharmLigneInventaireId(int invId, int prodAttriId) {
		this.invId = invId;
		this.prodAttriId = prodAttriId;
	}

	public int getInvId() {
		return this.invId;
	}

	public void setInvId(int invId) {
		this.invId = invId;
	}

	public int getProdAttriId() {
		return this.prodAttriId;
	}

	public void setProdAttriId(int prodAttriId) {
		this.prodAttriId = prodAttriId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmLigneInventaireId))
			return false;
		PharmLigneInventaireId castOther = (PharmLigneInventaireId) other;

		return (this.getInvId() == castOther.getInvId()) && (this.getProdAttriId() == castOther.getProdAttriId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvId();
		result = 37 * result + this.getProdAttriId();
		return result;
	}

}
