package org.openmrs.module.pharmagest;
// Generated 24 mai 2017 16:53:10 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PharmAssurance generated by hbm2java
 */
public class PharmAssurance implements java.io.Serializable {

	private int assurId;
	private String assurLib;
	private Date assurDateSaisi;
	private Date assurDateModi;
	private String assurFlag;
	private String assurObserv;
	private String assurRef;
	private String assurAttri;
	private Set<PharmLigneAssurance> pharmLigneAssurances = new HashSet<PharmLigneAssurance>(0);

	public PharmAssurance() {
	}

	public PharmAssurance(int assurId) {
		this.assurId = assurId;
	}

	public PharmAssurance(int assurId, String assurLib, Date assurDateSaisi, Date assurDateModi, String assurFlag,
			String assurObserv, String assurRef, String assurAttri, Set<PharmLigneAssurance> pharmLigneAssurances) {
		this.assurId = assurId;
		this.assurLib = assurLib;
		this.assurDateSaisi = assurDateSaisi;
		this.assurDateModi = assurDateModi;
		this.assurFlag = assurFlag;
		this.assurObserv = assurObserv;
		this.assurRef = assurRef;
		this.assurAttri = assurAttri;
		this.pharmLigneAssurances = pharmLigneAssurances;
	}

	public int getAssurId() {
		return this.assurId;
	}

	public void setAssurId(int assurId) {
		this.assurId = assurId;
	}

	public String getAssurLib() {
		return this.assurLib;
	}

	public void setAssurLib(String assurLib) {
		this.assurLib = assurLib;
	}

	public Date getAssurDateSaisi() {
		return this.assurDateSaisi;
	}

	public void setAssurDateSaisi(Date assurDateSaisi) {
		this.assurDateSaisi = assurDateSaisi;
	}

	public Date getAssurDateModi() {
		return this.assurDateModi;
	}

	public void setAssurDateModi(Date assurDateModi) {
		this.assurDateModi = assurDateModi;
	}

	public String getAssurFlag() {
		return this.assurFlag;
	}

	public void setAssurFlag(String assurFlag) {
		this.assurFlag = assurFlag;
	}

	public String getAssurObserv() {
		return this.assurObserv;
	}

	public void setAssurObserv(String assurObserv) {
		this.assurObserv = assurObserv;
	}

	public String getAssurRef() {
		return this.assurRef;
	}

	public void setAssurRef(String assurRef) {
		this.assurRef = assurRef;
	}

	public String getAssurAttri() {
		return this.assurAttri;
	}

	public void setAssurAttri(String assurAttri) {
		this.assurAttri = assurAttri;
	}

	public Set<PharmLigneAssurance> getPharmLigneAssurances() {
		return this.pharmLigneAssurances;
	}

	public void setPharmLigneAssurances(Set<PharmLigneAssurance> pharmLigneAssurances) {
		this.pharmLigneAssurances = pharmLigneAssurances;
	}

}
