package org.openmrs.module.pharmagest;

// Generated 16 août 2015 03:07:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PharmMedecin generated by hbm2java
 */
public class PharmMedecin implements java.io.Serializable {

	private Integer medId;
	private String medCode;
	private String medNom;
	private String medPrenom;
	private String medAdresse;
	private String medTel;
	private Set<PharmOrdonnance> pharmOrdonnances = new HashSet<PharmOrdonnance>(
			0);

	public PharmMedecin() {
	}

	public PharmMedecin(String medCode, String medNom, String medPrenom,
			String medAdresse, String medTel,
			Set<PharmOrdonnance> pharmOrdonnances) {
		this.medCode = medCode;
		this.medNom = medNom;
		this.medPrenom = medPrenom;
		this.medAdresse = medAdresse;
		this.medTel = medTel;
		this.pharmOrdonnances = pharmOrdonnances;
	}

	public Integer getMedId() {
		return this.medId;
	}

	public void setMedId(Integer medId) {
		this.medId = medId;
	}

	public String getMedCode() {
		return this.medCode;
	}

	public void setMedCode(String medCode) {
		this.medCode = medCode;
	}

	public String getMedNom() {
		return this.medNom;
	}

	public void setMedNom(String medNom) {
		this.medNom = medNom;
	}

	public String getMedPrenom() {
		return this.medPrenom;
	}

	public void setMedPrenom(String medPrenom) {
		this.medPrenom = medPrenom;
	}

	public String getMedAdresse() {
		return this.medAdresse;
	}

	public void setMedAdresse(String medAdresse) {
		this.medAdresse = medAdresse;
	}

	public String getMedTel() {
		return this.medTel;
	}

	public void setMedTel(String medTel) {
		this.medTel = medTel;
	}

	public Set<PharmOrdonnance> getPharmOrdonnances() {
		return this.pharmOrdonnances;
	}

	public void setPharmOrdonnances(Set<PharmOrdonnance> pharmOrdonnances) {
		this.pharmOrdonnances = pharmOrdonnances;
	}

}
