package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrixProduit generated by hbm2java
 */
public class PrixProduit implements java.io.Serializable {

	private int prixId;
	private Integer prixAchat;
	private Integer prixVente;
	private Date prixDateEff;
	private Boolean prixFlagActif;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public PrixProduit() {
	}

	public PrixProduit(int prixId) {
		this.prixId = prixId;
	}

	public PrixProduit(int prixId, Integer prixAchat, Integer prixVente,
			Date prixDateEff, Boolean prixFlagActif, Set<Produit> produits) {
		this.prixId = prixId;
		this.prixAchat = prixAchat;
		this.prixVente = prixVente;
		this.prixDateEff = prixDateEff;
		this.prixFlagActif = prixFlagActif;
		this.produits = produits;
	}

	public int getPrixId() {
		return this.prixId;
	}

	public void setPrixId(int prixId) {
		this.prixId = prixId;
	}

	public Integer getPrixAchat() {
		return this.prixAchat;
	}

	public void setPrixAchat(Integer prixAchat) {
		this.prixAchat = prixAchat;
	}

	public Integer getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(Integer prixVente) {
		this.prixVente = prixVente;
	}

	public Date getPrixDateEff() {
		return this.prixDateEff;
	}

	public void setPrixDateEff(Date prixDateEff) {
		this.prixDateEff = prixDateEff;
	}

	public Boolean getPrixFlagActif() {
		return this.prixFlagActif;
	}

	public void setPrixFlagActif(Boolean prixFlagActif) {
		this.prixFlagActif = prixFlagActif;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
