package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme implements java.io.Serializable {

	private int programId;
	private String programLib;
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);
	private Set<Stocker> stockers = new HashSet<Stocker>(0);
	private Set<Operation> operations = new HashSet<Operation>(0);
	private Set<Regime> regimes = new HashSet<Regime>(0);
	private Set<LigneInventaire> ligneInventaires = new HashSet<LigneInventaire>(
			0);
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Programme() {
	}

	public Programme(int programId) {
		this.programId = programId;
	}

	public Programme(int programId, String programLib,
			Set<Ordonnance> ordonnances, Set<Stocker> stockers,
			Set<Operation> operations, Set<Regime> regimes,
			Set<LigneInventaire> ligneInventaires, Set<Produit> produits) {
		this.programId = programId;
		this.programLib = programLib;
		this.ordonnances = ordonnances;
		this.stockers = stockers;
		this.operations = operations;
		this.regimes = regimes;
		this.ligneInventaires = ligneInventaires;
		this.produits = produits;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public String getProgramLib() {
		return this.programLib;
	}

	public void setProgramLib(String programLib) {
		this.programLib = programLib;
	}

	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

	public Set<Stocker> getStockers() {
		return this.stockers;
	}

	public void setStockers(Set<Stocker> stockers) {
		this.stockers = stockers;
	}

	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

	public Set<Regime> getRegimes() {
		return this.regimes;
	}

	public void setRegimes(Set<Regime> regimes) {
		this.regimes = regimes;
	}

	public Set<LigneInventaire> getLigneInventaires() {
		return this.ligneInventaires;
	}

	public void setLigneInventaires(Set<LigneInventaire> ligneInventaires) {
		this.ligneInventaires = ligneInventaires;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
