package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Regime generated by hbm2java
 */
public class Regime implements java.io.Serializable {

	private int regimId;
	private Programme programme;
	private String regimLib;
	private Set<Produit> produits = new HashSet<Produit>(0);
	private Set<PatientComplement> patientComplements = new HashSet<PatientComplement>(
			0);
	private Set<Ordonnance> ordonnances = new HashSet<Ordonnance>(0);

	public Regime() {
	}

	public Regime(int regimId, Programme programme) {
		this.regimId = regimId;
		this.programme = programme;
	}

	public Regime(int regimId, Programme programme, String regimLib,
			Set<Produit> produits, Set<PatientComplement> patientComplements,
			Set<Ordonnance> ordonnances) {
		this.regimId = regimId;
		this.programme = programme;
		this.regimLib = regimLib;
		this.produits = produits;
		this.patientComplements = patientComplements;
		this.ordonnances = ordonnances;
	}

	public int getRegimId() {
		return this.regimId;
	}

	public void setRegimId(int regimId) {
		this.regimId = regimId;
	}

	public Programme getProgramme() {
		return this.programme;
	}

	public void setProgramme(Programme programme) {
		this.programme = programme;
	}

	public String getRegimLib() {
		return this.regimLib;
	}

	public void setRegimLib(String regimLib) {
		this.regimLib = regimLib;
	}

	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

	public Set<PatientComplement> getPatientComplements() {
		return this.patientComplements;
	}

	public void setPatientComplements(Set<PatientComplement> patientComplements) {
		this.patientComplements = patientComplements;
	}

	public Set<Ordonnance> getOrdonnances() {
		return this.ordonnances;
	}

	public void setOrdonnances(Set<Ordonnance> ordonnances) {
		this.ordonnances = ordonnances;
	}

}
