package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

/**
 * StockerId generated by hbm2java
 */
public class StockerId implements java.io.Serializable {

	private int prodId;
	private int programId;

	public StockerId() {
	}

	public StockerId(int prodId, int programId) {
		this.prodId = prodId;
		this.programId = programId;
	}

	public int getProdId() {
		return this.prodId;
	}

	public void setProdId(int prodId) {
		this.prodId = prodId;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockerId))
			return false;
		StockerId castOther = (StockerId) other;

		return (this.getProdId() == castOther.getProdId())
				&& (this.getProgramId() == castOther.getProgramId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProdId();
		result = 37 * result + this.getProgramId();
		return result;
	}

}
