package org.openmrs.module.pharmagest;

// Generated 2 juil. 2015 23:11:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Stocker generated by hbm2java
 */
public class Stocker implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StockerId id;
	private Programme programme;
	private Produit produit;
	private Integer stockQte;
	private Integer stockQteMin;
	private Integer stockQteMax;
	private Date stockDateStock;
	private Date stockDatePeremp;

	public Stocker() {
	}

	public Stocker(StockerId id, Programme programme, Produit produit) {
		this.id = id;
		this.programme = programme;
		this.produit = produit;
	}

	public Stocker(StockerId id, Programme programme, Produit produit,
			Integer stockQte, Integer stockQteMin, Integer stockQteMax,
			Date stockDateStock, Date stockDatePeremp) {
		this.id = id;
		this.programme = programme;
		this.produit = produit;
		this.stockQte = stockQte;
		this.stockQteMin = stockQteMin;
		this.stockQteMax = stockQteMax;
		this.stockDateStock = stockDateStock;
		this.stockDatePeremp = stockDatePeremp;
	}

	public StockerId getId() {
		return this.id;
	}

	public void setId(StockerId id) {
		this.id = id;
	}

	public Programme getProgramme() {
		return this.programme;
	}

	public void setProgramme(Programme programme) {
		this.programme = programme;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Integer getStockQte() {
		return this.stockQte;
	}

	public void setStockQte(Integer stockQte) {
		this.stockQte = stockQte;
	}

	public Integer getStockQteMin() {
		return this.stockQteMin;
	}

	public void setStockQteMin(Integer stockQteMin) {
		this.stockQteMin = stockQteMin;
	}

	public Integer getStockQteMax() {
		return this.stockQteMax;
	}

	public void setStockQteMax(Integer stockQteMax) {
		this.stockQteMax = stockQteMax;
	}

	public Date getStockDateStock() {
		return this.stockDateStock;
	}

	public void setStockDateStock(Date stockDateStock) {
		this.stockDateStock = stockDateStock;
	}

	public Date getStockDatePeremp() {
		return this.stockDatePeremp;
	}

	public void setStockDatePeremp(Date stockDatePeremp) {
		this.stockDatePeremp = stockDatePeremp;
	}

}
